// 制作者が独自に作成したQA基礎問題。公式問題・公式本文は使用しない。
export const questions = [
    {
        id: 'qa-basic-001',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストの目的',
        question: '開発中の機能をテストする目的として、最も適切なものはどれですか？',
        choices: ['品質に関する情報を集め、判断に役立てる', '不具合が一件もないと証明する', '開発者の作業速度だけを評価する', '仕様書を自動的に完成させる'],
        correctAnswerIndex: 0,
        explanation: 'テストは問題を見つけるだけでなく、現在の品質や残るリスクを把握し、修正やリリースの判断材料を増やす活動です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-002',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '早期確認',
        question: '要件を決める段階で、曖昧な表現をレビューする利点はどれですか？',
        choices: ['本番障害を必ずゼロにできる', '実装後の手戻りを減らしやすい', 'テスト実行が不要になる', '利用者への確認が不要になる'],
        correctAnswerIndex: 1,
        explanation: '曖昧さを早く見つけるほど、設計や実装が進んだ後に直す範囲を小さくできます。ただし、後工程の確認が不要になるわけではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-003',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '期待結果',
        question: 'テストケースに期待結果を書く主な理由はどれですか？',
        choices: ['入力値を隠すため', '実行時間を必ず短くするため', '実際の結果が正しいか判断できるようにする', '担当者名を記録するためだけ'],
        correctAnswerIndex: 2,
        explanation: '期待結果が明確なら、実際の結果との差を具体的に比較できます。判断基準がないテストは、成功か失敗かが人によって変わりやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-004',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '同値グループ',
        question: '年齢入力が18歳以上を受け付ける画面で、同じ扱いになる値をまとめて考えるとき、適切な分け方はどれですか？',
        choices: ['偶数と奇数だけ', '一桁と二桁だけ', '入力した曜日ごと', '18歳未満と18歳以上'],
        correctAnswerIndex: 3,
        explanation: '判定条件が18歳以上かどうかなので、結果が同じになる18歳未満と18歳以上に分けると、代表値を選びやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-005',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '境界値',
        question: '数量が1個から10個まで入力できる場合、端の不具合を探すために優先したい値の組み合わせはどれですか？',
        choices: ['3、4、5、6', '0、1、10、11', '2、4、6、8', '1、3、7、9'],
        correctAnswerIndex: 1,
        explanation: '条件が切り替わる直前・直後と、許可範囲の両端を確認します。端では比較演算子の間違いなどが起きやすいためです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-006',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '状態変化',
        question: 'ログインを3回失敗するとアカウントが一時停止する機能で、特に確認すべき流れはどれですか？',
        choices: ['画面の背景色だけを変える流れ', '利用者名を毎回同じにする流れ', '失敗回数が2回から3回へ変わる流れ', '成功時の時刻だけを記録する流れ'],
        correctAnswerIndex: 2,
        explanation: '状態が通常から一時停止へ切り替わる境目を確認すると、回数の数え方や状態更新の誤りを見つけやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-007',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスク優先度',
        question: 'テスト時間が限られているとき、最初に確認する対象として妥当なのはどれですか？',
        choices: ['最近追加された文字色だけ', '利用されない管理メモ', '担当者が最も書きやすいテストだけ', '発生しやすく、起きた場合の影響も大きい機能'],
        correctAnswerIndex: 3,
        explanation: '起きやすさと影響の大きさを合わせて考えると、限られた時間を重大な問題の発見に使いやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-008',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '不具合報告',
        question: '再現しにくい不具合を報告するとき、最も役立つ情報はどれですか？',
        choices: ['発見者の感想だけ', '操作手順、環境、実際の結果、期待した結果', '画面名だけ', '修正担当者の予想だけ'],
        correctAnswerIndex: 1,
        explanation: '再現条件と結果の差が具体的だと、調査する人が同じ状況を作り、原因を絞り込みやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-009',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '回帰確認',
        question: '料金計算の不具合を修正した後、関連する割引計算も確認する理由はどれですか？',
        choices: ['修正内容を元に戻すため', '仕様を自動変更するため', '修正が既存機能へ影響していないか確かめるため', '不具合報告を削除するため'],
        correctAnswerIndex: 2,
        explanation: '変更は周辺の処理に思わぬ影響を与えることがあります。修正箇所だけでなく、関係する既存機能も確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-010',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '探索的な確認',
        question: '仕様書だけでは利用方法を予測しにくい新機能で、短時間に気づきを得る方法として適切なのはどれですか？',
        choices: ['結果を記録せず無計画に触る', '正常系を一度だけ実行する', '利用者の行動を想定しない', '目的と時間を決め、操作しながら次の確認を考える'],
        correctAnswerIndex: 3,
        explanation: '確認の目的と時間枠を決め、得た情報を次の操作へ反映すると、未知のリスクを探りながら記録も残せます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-011',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '静的な確認',
        question: 'プログラムを動かさずに行える品質確認はどれですか？',
        choices: ['本番環境で負荷をかける', '仕様書やコードを読み合わせる', '画面を操作して結果を見る', '通信を実際に切断する'],
        correctAnswerIndex: 1,
        explanation: '文書やコードのレビューは、実行前でも矛盾、抜け、読みにくさなどを見つけられる確認方法です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'qa-basic-012',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '完了判断',
        question: 'リリース前のテスト完了を判断するとき、確認材料として最も適切なものはどれですか？',
        choices: ['担当者の気分だけ', 'テスト件数の多さだけ', '実行結果、未解決の問題、残るリスク', '予定日を過ぎたかどうかだけ'],
        correctAnswerIndex: 2,
        explanation: '件数だけでなく、何が確認できたか、何が未確認か、どの問題が残るかを合わせて判断します。',
        reviewerStatus: 'reviewed',
    },
];

export const assumedProblems = questions;
export const mockExamQuestions = questions;
