// 制作者が独自に作成したFoundation Level学習問題。公式問題・公式本文は使用しない。
export const questions = [
    {
        id: 'fl-001',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストの目的',
        question: '開発中の機能をテストする目的として、最も適切なものはどれですか？',
        choices: ['品質に関する情報を集め、判断に役立てる', '不具合が一件もないと証明する', '開発者の作業速度だけを評価する', '仕様書を自動的に完成させる'],
        correctAnswerIndex: 0,
        explanation: 'テストは問題を見つけるだけでなく、現在の品質や残るリスクを把握し、修正やリリースの判断材料を増やす活動です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-002',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '早期確認',
        question: '要件を決める段階で、曖昧な表現をレビューする利点はどれですか？',
        choices: ['本番障害を必ずゼロにできる', '実装後の手戻りを減らしやすい', 'テスト実行が不要になる', '利用者への確認が不要になる'],
        correctAnswerIndex: 1,
        explanation: '曖昧さを早く見つけるほど、設計や実装が進んだ後に直す範囲を小さくできます。ただし、後工程の確認が不要になるわけではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-003',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '期待結果',
        question: 'テストケースに期待結果を書く主な理由はどれですか？',
        choices: ['入力値を隠すため', '実行時間を必ず短くするため', '実際の結果が正しいか判断できるようにする', '担当者名を記録するためだけ'],
        correctAnswerIndex: 2,
        explanation: '期待結果が明確なら、実際の結果との差を具体的に比較できます。判断基準がないテストは、成功か失敗かが人によって変わりやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-004',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '同値グループ',
        question: '年齢入力が18歳以上を受け付ける画面で、同じ扱いになる値をまとめて考えるとき、適切な分け方はどれですか？',
        choices: ['偶数と奇数だけ', '一桁と二桁だけ', '入力した曜日ごと', '18歳未満と18歳以上'],
        correctAnswerIndex: 3,
        explanation: '判定条件が18歳以上かどうかなので、結果が同じになる18歳未満と18歳以上に分けると、代表値を選びやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-005',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '境界値',
        question: '数量が1個から10個まで入力できる場合、端の不具合を探すために優先したい値の組み合わせはどれですか？',
        choices: ['3、4、5、6', '0、1、10、11', '2、4、6、8', '1、3、7、9'],
        correctAnswerIndex: 1,
        explanation: '条件が切り替わる直前・直後と、許可範囲の両端を確認します。端では比較演算子の間違いなどが起きやすいためです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-006',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '状態変化',
        question: 'ログインを3回失敗するとアカウントが一時停止する機能で、特に確認すべき流れはどれですか？',
        choices: ['画面の背景色だけを変える流れ', '利用者名を毎回同じにする流れ', '失敗回数が2回から3回へ変わる流れ', '成功時の時刻だけを記録する流れ'],
        correctAnswerIndex: 2,
        explanation: '状態が通常から一時停止へ切り替わる境目を確認すると、回数の数え方や状態更新の誤りを見つけやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-007',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスク優先度',
        question: 'テスト時間が限られているとき、最初に確認する対象として妥当なのはどれですか？',
        choices: ['最近追加された文字色だけ', '利用されない管理メモ', '担当者が最も書きやすいテストだけ', '発生しやすく、起きた場合の影響も大きい機能'],
        correctAnswerIndex: 3,
        explanation: '起きやすさと影響の大きさを合わせて考えると、限られた時間を重大な問題の発見に使いやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-008',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '不具合報告',
        question: '再現しにくい不具合を報告するとき、最も役立つ情報はどれですか？',
        choices: ['発見者の感想だけ', '操作手順、環境、実際の結果、期待した結果', '画面名だけ', '修正担当者の予想だけ'],
        correctAnswerIndex: 1,
        explanation: '再現条件と結果の差が具体的だと、調査する人が同じ状況を作り、原因を絞り込みやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-009',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '回帰確認',
        question: '料金計算の不具合を修正した後、関連する割引計算も確認する理由はどれですか？',
        choices: ['修正内容を元に戻すため', '仕様を自動変更するため', '修正が既存機能へ影響していないか確かめるため', '不具合報告を削除するため'],
        correctAnswerIndex: 2,
        explanation: '変更は周辺の処理に思わぬ影響を与えることがあります。修正箇所だけでなく、関係する既存機能も確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-010',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '探索的な確認',
        question: '仕様書だけでは利用方法を予測しにくい新機能で、短時間に気づきを得る方法として適切なのはどれですか？',
        choices: ['結果を記録せず無計画に触る', '正常系を一度だけ実行する', '利用者の行動を想定しない', '目的と時間を決め、操作しながら次の確認を考える'],
        correctAnswerIndex: 3,
        explanation: '確認の目的と時間枠を決め、得た情報を次の操作へ反映すると、未知のリスクを探りながら記録も残せます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-011',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '静的な確認',
        question: 'プログラムを動かさずに行える品質確認はどれですか？',
        choices: ['本番環境で負荷をかける', '仕様書やコードを読み合わせる', '画面を操作して結果を見る', '通信を実際に切断する'],
        correctAnswerIndex: 1,
        explanation: '文書やコードのレビューは、実行前でも矛盾、抜け、読みにくさなどを見つけられる確認方法です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-012',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '完了判断',
        question: 'リリース前のテスト完了を判断するとき、確認材料として最も適切なものはどれですか？',
        choices: ['担当者の気分だけ', 'テスト件数の多さだけ', '実行結果、未解決の問題、残るリスク', '予定日を過ぎたかどうかだけ'],
        correctAnswerIndex: 2,
        explanation: '件数だけでなく、何が確認できたか、何が未確認か、どの問題が残るかを合わせて判断します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-013',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストレベル',
        question: '新しく開発した決済モジュールを、既存の注文管理システムと組み合わせて動作確認したい。この場面に最も適したテストレベルはどれか。',
        choices: ['単体テスト', '結合テスト', 'システムテスト', '受入テスト'],
        correctAnswerIndex: 1,
        explanation: '複数のモジュールやコンポーネントを組み合わせてインターフェース・連携を確認するのは結合テストの目的です。単体は個別機能、システムは全体統合後、受入はユーザー承認確認のフェーズで実施します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-014',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストタイプ',
        question: 'ECサイトのチェックアウト機能が仕様どおりに動くか確認するテストはどのタイプに分類されるか。',
        choices: ['非機能テスト', '構造テスト', '機能テスト', '変更関連テスト'],
        correctAnswerIndex: 2,
        explanation: '機能テストはシステムが仕様で定められた機能を正しく実行するかを検証します。非機能は性能・セキュリティなど品質特性、構造はコード内部構造、変更関連は修正後の影響確認が目的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-015',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ブラックボックステスト',
        question: 'テスト担当者がソースコードを参照せず、入力と出力の組み合わせのみを使って検証を行った。この手法の特徴として正しいのはどれか。',
        choices: ['コードの分岐網羅率を高めることを目的とする', '内部実装の知識がなくても仕様に基づいてテスト設計できる', 'テスト担当者はプログラミング言語の深い知識が必要である', 'ステートメントカバレッジを測定することが主な目的である'],
        correctAnswerIndex: 1,
        explanation: 'ブラックボックステストは内部実装を意識せず仕様や要件に基づいて設計する手法です。コードへのアクセスや知識が不要なため、ユーザー視点のテストに適しています。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-016',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '決定表テスト',
        question: 'ローン審査システムで「年収300万円以上」かつ「勤続年数2年以上」を満たす場合に承認するルールがある。条件の組み合わせを漏れなく網羅したい場合に有効なテスト設計技法はどれか。',
        choices: ['境界値分析', '決定表テスト', 'ペアワイズテスト', '状態遷移テスト'],
        correctAnswerIndex: 1,
        explanation: '決定表テストは複数の条件とその組み合わせに対応するアクションを表形式で整理し、論理的な組み合わせを網羅する技法です。ビジネスルールが複数条件の組み合わせで決まる場面に特に有効です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-017',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ユースケーステスト',
        question: 'オンライン予約システムで「会員がログインして座席を選び、決済して予約確定するまで」の一連の操作を検証したい。最も適した設計技法はどれか。',
        choices: ['同値分割法', '決定表テスト', 'ユースケーステスト', '境界値分析'],
        correctAnswerIndex: 2,
        explanation: 'ユースケーステストはユーザーとシステムのやり取りを一連のシナリオとして設計し、エンドツーエンドの業務フローを検証する技法です。実際の利用場面に沿った統合動作の確認に適しています。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-018',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ペアワイズテスト',
        question: 'OS3種×ブラウザ4種×言語設定2種の組み合わせをテストしたいが、全組み合わせ24件の実施は工数的に困難である。テストケース数を削減しながら2因子間のすべての組み合わせを網羅する技法はどれか。',
        choices: ['ユースケーステスト', 'ペアワイズテスト', '決定表テスト', '同値分割法'],
        correctAnswerIndex: 1,
        explanation: 'ペアワイズテスト（オールペア法）は任意の2因子の組み合わせをすべて少なくとも1回カバーするようテストケースを最小化する技法です。多パラメータの組み合わせ爆発を抑えながら効率よく欠陥を検出できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-019',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト計画',
        question: 'テストマネージャーがプロジェクト開始時に作成するテスト計画書に含まれる内容として、最も適切なものはどれか。',
        choices: ['各テストケースの詳細な手順と期待結果', 'テストの目的・スコープ・スケジュール・必要リソース', '実行したテストケースの合否ログ', 'システムの全機能一覧と優先度'],
        correctAnswerIndex: 1,
        explanation: 'テスト計画書にはテストの目的、範囲、アプローチ、スケジュール、必要リソース、リスクと対応策などを記載します。個別テストケースの詳細手順はテスト仕様書、合否ログはテスト報告書に記録します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-020',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストモニタリングとコントロール',
        question: 'テスト実施中にバグ件数が予想を大幅に超え、残りスケジュールで完了できないことが判明した。テストマネージャーが取るべきコントロール活動として最も適切なのはどれか。',
        choices: ['テスト担当者に残業を依頼して計画どおりに終わらせる', 'テスト進捗状況をステークホルダーに報告し、スコープや日程の調整を協議する', 'バグ件数の多いモジュールのテストを中止して全体完了率を上げる', '次のフェーズのテストを先行して開始し、後から今フェーズを補完する'],
        correctAnswerIndex: 1,
        explanation: 'テストコントロールはモニタリングで得た情報をもとに計画を見直し、スコープ・リソース・スケジュールの調整をステークホルダーと合意する活動です。問題を隠したり独断でスコープを削減するのは適切ではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-021',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストツール',
        question: 'CI/CDパイプラインに組み込んで、コードがリポジトリにプッシュされるたびにテストスクリプトを自動実行させたい。この用途に直接対応するツールカテゴリはどれか。',
        choices: ['欠陥管理ツール', 'テスト実行ツール', '静的解析ツール', '要件管理ツール'],
        correctAnswerIndex: 1,
        explanation: 'テスト実行ツールはスクリプト化されたテストを自動実行し結果を記録します。CI/CDへの統合により継続的なフィードバックが得られます。欠陥管理はバグ追跡、静的解析はコード解析、要件管理は要求のトレースに用います。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-022',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト自動化',
        question: 'テスト自動化を導入したチームが「自動テストは一度作れば変更不要」と考え、仕様変更後もスクリプトを更新しなかった。このリスクとして最も深刻なのはどれか。',
        choices: ['自動化ツールのライセンス費用が増大する', 'テスト実行が遅くなりCIパイプラインが詰まる', '古いスクリプトが誤って成功を返し、実際の欠陥を見逃す可能性がある', 'チームメンバーの手動テストスキルが低下する'],
        correctAnswerIndex: 2,
        explanation: '自動テストスクリプトは仕様変更に合わせて継続的にメンテナンスしなければ、変更後の誤った実装に対しても成功判定してしまうことがあります。自動化には保守コストが伴うという認識が不可欠です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-023',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥の原因と影響',
        question: '開発者がAPIのタイムアウト値を設定し忘れたため、本番環境で外部サービス障害時にリクエストが無限待機してシステム全体が応答不能になった。この関係を正しく説明しているのはどれか。',
        choices: ['タイムアウト未設定が故障であり、応答不能が欠陥である', 'タイムアウト未設定が誤り（ミス）であり、欠陥がコードに混入し、障害時に故障として現れた', '応答不能が欠陥であり、タイムアウト未設定が根本原因となる故障である', 'すべての事象は等しく欠陥と呼ぶべきであり区別する必要はない'],
        correctAnswerIndex: 1,
        explanation: '人間の誤り（ミス）がソフトウェアに欠陥（バグ）を生み出し、その欠陥が特定条件下で実行されると故障（システムの誤動作）となります。原因と影響の連鎖を正しく理解することが根本対策につながります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-024',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ルートコーズ分析',
        question: '本番障害が発生したあと、チームが「なぜ入力値の検証が抜けていたか」を繰り返し掘り下げ、「レビュー手順書に検証項目が記載されていなかった」という根本原因を特定した。この活動を何というか。',
        choices: ['欠陥クラスタリング', 'ルートコーズ分析', 'リスクベーステスト', 'テストモニタリング'],
        correctAnswerIndex: 1,
        explanation: 'ルートコーズ分析（根本原因分析）は表面的な欠陥や障害を起点に、根本となる原因を組織的・プロセス的レベルまで掘り下げる活動です。再発防止策の立案に直結し、プロセス改善に活用されます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-025',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'バグのライフサイクル',
        question: 'テスト担当者が欠陥を発見して報告した後、開発者が修正を完了した。次にテスト担当者が取るべきアクションはどれか。',
        choices: ['欠陥をクローズしてステータスを「解決済み」にする', '同じモジュールで新たな欠陥を探して探索的テストを行う', '修正が正しく機能しているかを確認テスト（再テスト）で検証する', '欠陥管理ツールに同様の欠陥が他にないか検索する'],
        correctAnswerIndex: 2,
        explanation: '開発者が修正を完了したら、テスト担当者は報告した欠陥が正しく修正されているかを確認テスト（再テスト）で検証します。確認が取れて初めて欠陥をクローズできます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-026',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト報告書',
        question: 'テストプロジェクトの終了時に作成するドキュメントとして、テストの実施結果・カバレッジ・残留リスクをまとめたものはどれか。',
        choices: ['テスト計画書', 'テストケース仕様書', 'テスト報告書', 'テストアーキテクチャ設計書'],
        correctAnswerIndex: 2,
        explanation: 'テスト報告書（サマリーレポート）はテスト活動の結果を集約したドキュメントで、実施件数・合否・カバレッジ・未解決欠陥・残留リスクなどを記載します。ステークホルダーへのリリース判断根拠となります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-027',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '非機能テスト',
        question: 'フラッシュセール開始直後に数万件のリクエストが集中することを想定し、システムが応答時間の劣化なく処理できるかを検証したい。この目的に最も適したテストはどれか。',
        choices: ['セキュリティテスト', '負荷テスト', 'ユーザビリティテスト', '互換性テスト'],
        correctAnswerIndex: 1,
        explanation: '負荷テストは想定される高負荷条件下でシステムの性能（応答時間・スループット）が許容範囲内に収まるかを検証する非機能テストです。特定の同時ユーザー数やリクエスト量でのふるまいを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-028',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '受入テスト',
        question: 'システム開発の最終フェーズで、発注側の担当者がシステムを使って業務シナリオを実際に試し、契約要件を満たしているか確認するテストを何というか。',
        choices: ['システムテスト', '結合テスト', '受入テスト', '単体テスト'],
        correctAnswerIndex: 2,
        explanation: '受入テストはシステムがユーザーや発注者のビジネスニーズ・契約要件を満たすかをユーザー視点で確認するテストレベルです。正式なリリースや検収の判断基準となる重要なフェーズです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-029',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの独立性',
        question: '開発者が自分のコードを自分でテストする状況と、独立したテスト担当者がテストする状況を比較したとき、独立性を持つテスト担当者の利点として最も適切なのはどれか。',
        choices: ['テスト担当者はコードの仕様を最もよく理解しているため、欠陥を早く修正できる', '開発者が作り込んだ思い込みや前提を持たずに検証できるため、見落としを発見しやすい', '開発者より実行環境に詳しいため、環境起因の問題を効率よく解決できる', 'テスト担当者はコードを変更できないため、テスト結果が常に客観的になる'],
        correctAnswerIndex: 1,
        explanation: 'テスト担当者の独立性の主な利点は、開発者が持つ思い込みや認知バイアスなしに検証できることです。開発者は自分のコードの動作を前提に考えがちであり、独立した視点が欠陥発見率を高めます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-030',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストの原則',
        question: 'リリース直前に「すべての欠陥を見つけ、ゼロにしてからリリースする」という方針を立てた。このことに関してテストの原則として正しい見解はどれか。',
        choices: ['十分なテスト期間があれば全欠陥の検出は可能である', 'テストはすべての欠陥を証明できないが、欠陥がないことは証明できる', '完全なテストは不可能であり、欠陥ゼロを保証することはできない', 'リリース後にユーザーが使うことで残りの欠陥が自然に発見される'],
        correctAnswerIndex: 2,
        explanation: 'テストの原則のひとつとして「完全なテストは不可能」があります。あらゆる入力・条件の組み合わせを網羅することは現実的でなく、リスクに基づいて優先順位をつけてテストすることが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-031',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '確認テストと回帰テスト',
        question: '修正した欠陥が正しく直っているか確認した後、その修正が他の機能に悪影響を与えていないかも合わせて検証したい。後者の目的に対応するテストはどれか。',
        choices: ['確認テスト（再テスト）', '回帰テスト', '探索的テスト', 'スモークテスト'],
        correctAnswerIndex: 1,
        explanation: '回帰テストは変更（修正・追加・設定変更など）が意図しない副作用を引き起こしていないかを確認するテストです。確認テストは修正された欠陥そのものを検証するのに対し、回帰テストは周辺機能への影響を検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-032',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストオラクル',
        question: 'テストケースを設計する際に「何を期待結果とするか」の根拠として、テスト担当者が参照する既存ドキュメントを何というか。',
        choices: ['テストベース', 'テストオラクル', 'テストチャーター', 'テストハーネス'],
        correctAnswerIndex: 1,
        explanation: 'テストオラクルは期待結果を判断するための根拠・情報源であり、仕様書・ユーザーマニュアル・既存システムの動作などが該当します。テストベースはテストケースを導出するためのドキュメントや情報全般を指します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-033',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'ホワイトボックステストとカバレッジ',
        question: '決済処理のコードに対してホワイトボックステストを実施する場合、テスト設計の基盤となる情報はどれですか？',
        choices: ['画面のデザインモックアップ', 'コードの内部構造（分岐・ループ・パスなど）', 'エンドユーザーの操作シナリオ', '競合製品との機能比較表'],
        correctAnswerIndex: 1,
        explanation: 'ホワイトボックステストはソースコードの内部構造を可視化した状態でテストを設計します。分岐条件やパスを把握することで、カバレッジ基準に沿ったテストケースを導出できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-034',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '文書(ステートメント)カバレッジ',
        question: '次のコードに対してステートメントカバレッジ100%を達成するために最低限必要なテストケース数はいくつですか？「if(score>=60){ grade="合格"; } else { grade="不合格"; } return grade;」',
        choices: ['1件', '2件', '4件', '8件'],
        correctAnswerIndex: 1,
        explanation: 'このコードにはif分岐のthenブロックとelseブロックの2つの実行可能な文の集合があります。両方のブロックを少なくとも1回ずつ実行するには、score>=60のケースとscore<60のケースの2件が必要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-035',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '分岐カバレッジ',
        question: '「if(isLoggedIn && hasPurchased)」という条件を持つ処理で、分岐カバレッジ100%を達成するために必ず確認しなければならないことはどれですか？',
        choices: ['条件がtrueになるケースだけを確認する', 'isLoggedInだけがfalseのケースを確認する', '条件がtrueになるケースとfalseになるケースの両方を確認する', '全4通りの論理値の組み合わせをすべて確認する'],
        correctAnswerIndex: 2,
        explanation: '分岐カバレッジ（デシジョンカバレッジ）は各分岐点において真と偽の両方の結果を少なくとも1回ずつ実行することを要求します。条件式全体がtrueになるテストと、falseになるテストが最低限必要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-036',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの7原則（殺虫剤のパラドックス）',
        question: 'Webアプリのログイン画面に対して同じテストスクリプトを6ヶ月間使い続けているチームが「最近は欠陥がまったく検出されない」と報告しています。この状況で最も適切な対応はどれですか？',
        choices: ['欠陥がゼロになったのでテストを終了する', 'テストケースを定期的に見直し、新しい視点や条件を追加する', 'テスト実行頻度を2倍に増やす', 'テスト担当者を交代させる'],
        correctAnswerIndex: 1,
        explanation: '同じテストを繰り返すと、そのテストが発見できる欠陥は修正済みになり、新たな欠陥を見つけにくくなります（殺虫剤のパラドックス）。定期的にテストケースを更新・拡張することで検出能力を維持できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-037',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの7原則（欠陥クラスタリング）',
        question: '過去3リリースの欠陥データを分析したところ、全欠陥の75%が在庫管理モジュールの1ファイルに集中していました。次のテスト計画で最も合理的な判断はどれですか？',
        choices: ['全モジュールに均等にテスト時間を配分する', '欠陥が集中しているファイルへのテストリソースを増やす', '欠陥が少ないモジュールを優先的にテストする', '欠陥が集中しているファイルは安定しているとみなしてスキップする'],
        correctAnswerIndex: 1,
        explanation: '欠陥は一部のモジュールや機能に集中する傾向があります（欠陥クラスタリング）。過去の欠陥実績が多い箇所は今後も欠陥が発生しやすい傾向にあるため、リソースを重点配分することが効果的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-038',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの7原則（テストは状況に依存する）',
        question: '医療機器の制御ソフトウェアと、社内向けの勤怠管理Webアプリで、テストアプローチが異なる主な理由として最も適切なものはどれですか？',
        choices: ['どちらも同じアプローチを採用すべきであり、差は設けるべきでない', 'テスト担当者のスキルレベルによってアプローチを変える', '製品の用途・リスクレベル・品質要求によってテスト戦略は変わる', 'コード量が多い方に厳格なテストを適用する'],
        correctAnswerIndex: 2,
        explanation: 'テストのアプローチは製品の特性・業界規制・リスク・品質要求によって異なります。人命に関わる医療機器は規制や厳格な検証が必要であり、社内ツールとは求められる品質水準が根本的に異なります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-039',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの7原則（早期テスト）',
        question: '要件定義フェーズで作成した仕様書に矛盾が見つかった場合、設計・実装後まで放置した場合と比較して早期に修正することで最も期待できる効果はどれですか？',
        choices: ['リリース後のユーザー満足度が必ず向上する', '手戻りコストと修正範囲が小さくなる', '開発期間を半分に短縮できる', 'テストケースを作成する必要がなくなる'],
        correctAnswerIndex: 1,
        explanation: '欠陥は発見が遅くなるほど修正コストが増大します（早期テストの原則）。要件段階で矛盾を発見すれば、設計・コード・テスト資産への波及を防ぎ、修正範囲を最小限に抑えられます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-040',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '欠陥管理ツールの使い方',
        question: 'テスト中に発見した欠陥をJiraなどの欠陥管理ツールに登録する主な目的として最も適切なものはどれですか？',
        choices: ['開発者の作業時間を自動的に計算するため', '欠陥の状態・担当者・優先度を追跡し、修正プロセスを管理するため', 'テストコードを自動生成するため', '本番環境のサーバーログを監視するため'],
        correctAnswerIndex: 1,
        explanation: '欠陥管理ツールは欠陥を一元管理し、新規・調査中・修正済み・クローズなどの状態遷移を追跡します。担当者・優先度・再現手順などを記録することで、修正漏れや優先順位の混乱を防ぎます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-041',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト環境の準備',
        question: '本番環境に近い条件でシステムテストを実施したいが、本番DBに顧客の個人情報が含まれている。テスト環境のデータとして最も適切な対応はどれですか？',
        choices: ['本番DBをそのままコピーしてテスト環境に配置する', '個人情報をマスキングまたは匿名化したデータをテスト環境に用意する', '実データが必要なので本番環境で直接テストを実施する', 'データなしでテストを実施し、後で本番データで検証する'],
        correctAnswerIndex: 1,
        explanation: 'テスト環境では本番に近いデータ条件を再現しつつ、個人情報保護法などの規制に準拠する必要があります。マスキングや匿名化により、プライバシーリスクを排除しながらリアルなデータ条件でテストできます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-042',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'スタブとドライバー',
        question: '注文サービスが在庫サービスを呼び出す設計で、在庫サービスがまだ開発中のため単体テストができない。この状況で注文サービスをテストするための適切なアプローチはどれですか？',
        choices: ['在庫サービスの開発完了まで注文サービスのテストを待つ', '在庫サービスの代わりに決められた応答を返す簡易モジュール（スタブ）を作成して使う', '注文サービスのコードを在庫サービスが完成するまで変更しない', 'テスト担当者が手動で在庫サービスの動作を再現する'],
        correctAnswerIndex: 1,
        explanation: 'スタブはテスト対象のコンポーネントが依存する下位コンポーネントの代替品で、事前に定義した応答を返します。これにより依存コンポーネントの完成を待たずにテストを進められます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-043',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストハーネス',
        question: '自動テストを継続的に実行するために、テストフレームワーク・テストデータ・スタブ・ドライバーをまとめてテスト実行環境として整備したものを何と呼びますか？',
        choices: ['テストチャーター', 'テストオラクル', 'テストハーネス', 'テストログ'],
        correctAnswerIndex: 2,
        explanation: 'テストハーネスはテストを実行するために必要なすべての支援コンポーネント（テストフレームワーク・データ・スタブ・ドライバーなど）を組み合わせた実行基盤です。CI/CDパイプラインでの自動テストに欠かせない仕組みです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-044',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストダブル（モック）',
        question: '決済サービスとの連携テストで、実際の決済APIを呼び出すと課金が発生してしまいます。モックを使う場合の主な利点はどれですか？',
        choices: ['決済処理の実際の動作を完全に検証できる', '外部サービスへの依存をなくし、コスト・副作用なしに呼び出し動作を検証できる', 'APIのレスポンスタイムを正確に計測できる', 'セキュリティ脆弱性を自動的に発見できる'],
        correctAnswerIndex: 1,
        explanation: 'モックは外部サービスやコンポーネントを模倣するテストダブルです。実際のAPIを呼ばずに呼び出し回数・引数・戻り値を検証でき、課金・副作用・ネットワーク依存を排除してテストを安定させます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-045',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの優先順位付け',
        question: '300件のテストケースを2日間で実行しなければならない制約があります。テストの優先順位付けに最も適した基準の組み合わせはどれですか？',
        choices: ['テストケースの作成順番と担当者の好み', 'ビジネスリスク・欠陥発生可能性・影響度の高さ', 'テスト実行時間の短さだけ', '前回テストしてからの経過日数だけ'],
        correctAnswerIndex: 1,
        explanation: '時間制約下では、実行できなかったテストによるリスクを最小化することが重要です。ビジネスへの影響が大きく欠陥が発生しやすい機能を優先することで、限られたリソースを最も効果的に配分できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-046',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスクベーステスト',
        question: 'リスクベーステストの計画で「リスクレベル」を算出するために組み合わせる2つの要素はどれですか？',
        choices: ['テスト実行時間とテストケース数', '欠陥が発生する可能性と欠陥が発生した場合の影響の大きさ', '開発チームの規模とプロジェクトの予算', 'コードの行数と変更されたファイル数'],
        correctAnswerIndex: 1,
        explanation: 'リスクベーステストではリスクレベル＝発生可能性×影響度で優先順位を算出します。高確率で発生し、かつ重大な影響をもたらす項目を最優先でテストすることでリスク低減を効率化します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-047',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'エラー推測',
        question: 'ECサイトのカート機能をテストする際、経験豊富なテスト担当者が「数量に0やマイナス値を入力する」「同一商品を複数回追加する」といったケースを積極的にテストしました。この手法はどれですか？',
        choices: ['同値分割法', 'エラー推測', '分岐カバレッジ', 'ペアワイズテスト'],
        correctAnswerIndex: 1,
        explanation: 'エラー推測は過去の経験・欠陥パターン・直感をもとに欠陥が潜みやすい箇所を予測してテストケースを設計する手法です。境界値や異常系など「壊れやすい」入力を経験的に選択します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-048',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'チェックリストベーステスト',
        question: 'セキュリティテストの経験が少ないメンバーが脆弱性確認を担当します。テスト設計の効率と品質を確保するための最も適切な支援はどれですか？',
        choices: ['全テストケースをゼロから作成させる', '過去のセキュリティ欠陥パターンをまとめたチェックリストを提供し、それをもとにテストさせる', '経験のある担当者だけに任せてメンバーは関与させない', '仕様書を読むだけで済むよう詳細な仕様を書き直す'],
        correctAnswerIndex: 1,
        explanation: 'チェックリストベーステストは確認すべき項目を事前にリスト化し、それをもとにテストを実施する手法です。経験やドメイン知識の不足を補い、重要確認項目の抜け漏れを防ぐことができます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-049',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストチャーター（探索的テスト計画）',
        question: '探索的テストのセッションで「新規ユーザー登録フローの認証エラー処理をテストする。30分で実施し、エラーメッセージの正確さと画面遷移を確認する」と記述したドキュメントを何と呼びますか？',
        choices: ['テスト計画書', 'テストチャーター', 'テスト報告書', 'リリースノート'],
        correctAnswerIndex: 1,
        explanation: 'テストチャーターは探索的テストセッションの目的・対象・時間枠・確認観点を定めた軽量な計画ドキュメントです。詳細な手順書を作らず、テスト担当者の判断を活かしながら方向性を示します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-050',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'アジャイルとテスト',
        question: 'アジャイル開発でテスト担当者がスプリントの最初から参加し、要件の整理・受入条件の定義・テスト設計を並行して行います。この進め方の主な利点はどれですか？',
        choices: ['テストを最後にまとめることでレビュー工数を削減できる', '要件の曖昧さを早期に発見でき、受入条件が実装開始前に明確になる', '開発者がテストを書く必要がなくなる', '毎スプリントで完全な回帰テストを省略できる'],
        correctAnswerIndex: 1,
        explanation: 'アジャイルではテスト担当者がスプリント計画から参加することで、受入条件を早期に明確化し、実装とテストのずれを防げます。これはシフトレフトの考え方とも一致します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-051',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト駆動開発（TDD）',
        question: 'TDDの実践手順として正しい順序はどれですか？',
        choices: ['実装を書く→テストを書く→リファクタリングする', 'テストを書く→テストが失敗することを確認する→実装を書く→テストが通ることを確認する→リファクタリングする', 'テストを書く→リファクタリングする→実装を書く', 'テストと実装を同時に書く→リファクタリングする'],
        correctAnswerIndex: 1,
        explanation: 'TDDはRed-Green-Refactorのサイクルです。まず失敗するテストを書き（Red）、テストを通す最小限の実装をし（Green）、コードを整理します（Refactor）。この順序により設計が明確になり、過剰実装を防ぎます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-052',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '継続的インテグレーションとテスト',
        question: 'CI（継続的インテグレーション）パイプラインに自動テストを組み込む最大の利点はどれですか？',
        choices: ['テストケースを一切書かなくてよくなる', 'コードがマージされるたびに自動でビルド・テストが実行され、問題を早期に検出できる', '手動テストが完全に不要になる', 'リリース後の欠陥が必ずゼロになる'],
        correctAnswerIndex: 1,
        explanation: 'CIはコードのコミット・マージのたびに自動ビルドとテストを実行する仕組みです。問題を小さな変更単位で即座に検出できるため、修正コストが低く、統合時のリスクを最小化できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-053',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'シフトレフトテスト',
        question: 'シフトレフトテストの考え方として最も適切なものはどれですか？',
        choices: ['テストを開発の後半フェーズに集中させる', 'テスト活動をより早い開発フェーズから開始し、欠陥を上流で発見する', 'テストは本番リリース後のユーザーフィードバックで実施する', 'テスト担当者の左側に開発者を座らせることで連携を高める'],
        correctAnswerIndex: 1,
        explanation: 'シフトレフトはテストを開発プロセスの早い段階（左側）にシフトさせる考え方です。要件・設計段階からテストを関与させることで欠陥の早期発見と修正コストの低減を実現します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-054',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストのフィードバックループ',
        question: 'テスト実行後に欠陥が検出されたとき、開発者への通知・修正・再テストまでのサイクルを短くすることで得られる主な利点はどれですか？',
        choices: ['テストケースの総数が減少する', '欠陥の文脈が新鮮なうちに原因を特定・修正でき、手戻りコストが下がる', 'テスト環境の維持コストが不要になる', 'リリース後の機能追加が容易になる'],
        correctAnswerIndex: 1,
        explanation: '短いフィードバックループは、欠陥に関する文脈情報（コードの変更内容・意図）が開発者の記憶に新しいうちに修正できる利点があります。サイクルが長くなるほど調査コストと手戻り工数が増大します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-055',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'パフォーマンステスト',
        question: 'Webサービスで「ピーク時に1000ユーザーが同時アクセスしたとき、ページ表示が3秒以内であること」を検証するテストはどれですか？',
        choices: ['ユーザビリティテスト', 'セキュリティテスト', 'パフォーマンステスト', '互換性テスト'],
        correctAnswerIndex: 2,
        explanation: 'パフォーマンステストはシステムの応答速度・スループット・リソース利用率などの性能特性を定量的に評価します。同時接続ユーザー数に対する応答時間の検証はパフォーマンステストの典型的なシナリオです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-056',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ストレステスト',
        question: 'ECサイトで通常の5倍のトラフィックをかけ続け、システムが限界を超えた後にクラッシュせず正常にデグレードするかを確認したいと思います。この目的に最も適したテストはどれですか？',
        choices: ['ユニットテスト', 'ストレステスト', '受入テスト', 'スモークテスト'],
        correctAnswerIndex: 1,
        explanation: 'ストレステストはシステムが設計上限を超えた負荷条件下でどう振る舞うかを検証します。クラッシュ・データ破損の有無、負荷解除後の回復能力、グレースフルデグレードの確認が主な目的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-057',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '耐久テスト',
        question: '画像処理サービスに対して通常の処理負荷を72時間連続で与え、メモリリークや性能劣化がないか確認するテストを何と呼びますか？',
        choices: ['スモークテスト', '探索的テスト', '耐久テスト（ソークテスト）', 'パイロットテスト'],
        correctAnswerIndex: 2,
        explanation: '耐久テスト（ソークテスト・持続テストとも呼ぶ）は長時間にわたって負荷をかけ続けることで、メモリリーク・ファイルハンドルの枯渇・性能の漸進的劣化などを検出する非機能テストです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-058',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '拡張性テスト',
        question: 'クラウド上で稼働するAPIサービスに対し、ユーザー数が10倍になったときにスケールアウトして性能を維持できるかを確認したい場合、最も適したテストはどれですか？',
        choices: ['ユーザビリティテスト', '拡張性テスト（スケーラビリティテスト）', '移植性テスト', '国際化テスト'],
        correctAnswerIndex: 1,
        explanation: '拡張性テスト（スケーラビリティテスト）はリソースやユーザー数が増加したときにシステムが要求された性能・機能を維持できるかを検証します。水平スケールアウト能力の確認に特に有効です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-059',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'アクセシビリティテスト',
        question: '視覚障害を持つユーザーがスクリーンリーダーでWebサイトを利用できるかを確認するテストで、特に重要な確認項目はどれですか？',
        choices: ['画像のファイルサイズとロード時間', '画像へのalt属性・フォームラベル・見出し構造の適切な設定', 'ページのカラーテーマと配色', 'アニメーションの速度と滑らかさ'],
        correctAnswerIndex: 1,
        explanation: 'スクリーンリーダーはHTML構造を音声化するため、画像のalt属性・フォームラベル・適切な見出し階層が必須です。これらが欠けていると視覚障害ユーザーがコンテンツの意味を理解できなくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-060',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ローカライゼーションテスト',
        question: '日本語版アプリを英語・フランス語・アラビア語版に展開する際、ローカライゼーションテストで最も注意すべき観点はどれですか？',
        choices: ['サーバーのCPU使用率への影響', '翻訳テキストの表示崩れ・文字化け・RTL（右から左）レイアウトの確認', 'データベースの検索速度への影響', 'CIパイプラインの実行時間'],
        correctAnswerIndex: 1,
        explanation: 'ローカライゼーションテストでは各言語固有の問題（テキスト展開によるUI崩れ・日本語フォント表示・アラビア語などのRTLレイアウト・日付や通貨形式）を中心に検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-061',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '互換性テスト（ブラウザ・OS）',
        question: 'WebアプリのCSS GridレイアウトがChrome・Firefox・Safariで正しく表示されるかを確認するテストの目的として最も適切なものはどれですか？',
        choices: ['サーバー側のAPI仕様の正確さを確認する', 'ブラウザ間の実装差異によるレイアウト崩れや機能の違いを検出する', 'ページの読み込み速度を最大化する', 'テストケースの網羅率を上げる'],
        correctAnswerIndex: 1,
        explanation: '互換性テストはブラウザ・OSなどの環境差異でソフトウェアの動作に違いが生じないかを検証します。CSSやJavaScriptのブラウザごとの実装差異は見た目や機能に影響するため、主要環境での確認が必要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-062',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'インストール・アンインストールテスト',
        question: 'デスクトップアプリのインストールテストで確認すべき重要な項目として最も適切なものはどれですか？',
        choices: ['アプリのUIデザインが仕様どおりか', 'インストール・アップグレード・アンインストール後にシステムに不要なファイルやレジストリが残らないか', 'APIのレスポンス時間が許容範囲内か', 'データベースのインデックス設計が最適か'],
        correctAnswerIndex: 1,
        explanation: 'インストール・アンインストールテストでは正常な導入・更新・削除に加え、インストール失敗時のロールバック・アンインストール後の残留ファイル・レジストリのクリーンアップを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-063',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'データ移行テスト',
        question: '旧システムから新システムへのデータ移行テストで、最も優先して確認すべきことはどれですか？',
        choices: ['新システムの画面デザインが改善されているか', '移行後のデータが件数・内容ともに正確に引き継がれ、欠損・文字化け・変換誤りがないか', '新システムの開発にかかったコストが予算内か', '移行ツールのコード行数が適切か'],
        correctAnswerIndex: 1,
        explanation: 'データ移行テストの核心は移行後のデータ整合性の確認です。レコード件数の一致・データ変換ルールの正確な適用・文字コード変換による文字化け・重複・欠落がないことを検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-064',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'APIテスト',
        question: '商品検索APIに対してリクエストパラメーターのバリデーション確認をしたい。最も確認すべきテストケースの組み合わせはどれですか？',
        choices: ['正常なパラメーターのみで呼び出す', '必須パラメーター欠損・不正な型・範囲外の値・空文字など異常系のレスポンスを確認する', 'レスポンスのJSONフォーマットだけを確認する', 'APIのソースコードを直接読んで仕様を理解する'],
        correctAnswerIndex: 1,
        explanation: 'APIテストでは正常系だけでなく、必須項目の欠如・型不正・範囲外値などの異常系でも適切なエラーレスポンス（ステータスコード・エラーメッセージ）が返るかを確認することが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-065',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'UIテスト vs APIテスト',
        question: 'Eコマースサービスの在庫数更新ロジックのテストを設計する際、UIテストよりAPIテストを優先する主な理由はどれですか？',
        choices: ['UIテストはブラウザが必要なためコストが高い、という理由だけ', 'APIテストはUIの変更に影響されにくく、ビジネスロジックをより直接・高速に検証できる', 'UIテストは自動化が不可能なため', 'APIはHTML構造を理解しなくてよいため担当者の学習コストが下がる'],
        correctAnswerIndex: 1,
        explanation: 'APIテストはUIの変更に左右されず安定しており、ビジネスロジックを直接・高速に検証できます。UIテストはユーザー体験の確認に向いていますが、ロジック検証にはAPIテストが効率的で保守コストも低くなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-066',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'エンドツーエンドテスト',
        question: 'ユーザーが商品を検索→カートに追加→支払い→注文確認メール受信までの全流れをユーザー視点で検証するテストを何と呼びますか？',
        choices: ['単体テスト', 'APIテスト', 'エンドツーエンドテスト（E2Eテスト）', '静的解析'],
        correctAnswerIndex: 2,
        explanation: 'エンドツーエンドテスト（E2Eテスト）は実際のユーザー体験に沿ってシステム全体のフローを端から端まで検証します。複数のシステム・サービス・UI・バックエンドが連携した状態で動作することを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-067',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'スモークテストとサニティテスト',
        question: '新しいビルドをテスト環境にデプロイした直後、詳細なテストを始める前に「ログインできるか・主要機能が起動するか」だけをざっくり確認します。この確認を何と呼びますか？',
        choices: ['回帰テスト', 'サニティテスト', 'スモークテスト', '受入テスト'],
        correctAnswerIndex: 2,
        explanation: 'スモークテストはビルドが基本的な動作をするかを短時間で確認し、テストを続行できるかを判断するための最小限の検証です。致命的な問題があれば詳細テストの前に早期に発見できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-068',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '回帰テストの自動化',
        question: '毎スプリントで回帰テストを実施するアジャイルチームが、増え続けるテストケースの手動実行に時間がかかりすぎています。最も適切な対策はどれですか？',
        choices: ['テストケース数を減らして実施時間を短縮する', '安定したテストケースを自動化し、CIパイプラインで毎回自動実行する', '回帰テストを隔週に減らす', '新機能のテストだけに集中し、回帰テストをやめる'],
        correctAnswerIndex: 1,
        explanation: '回帰テストは変更のたびに繰り返し実行する必要があるため、自動化の費用対効果が高い領域です。安定したテストケースを自動化してCIに組み込むことで、品質を維持しながら実行コストを大幅に削減できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-069',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストカバレッジメトリクス',
        question: '1000件のテストケースのうち850件を実行し、そのうち800件がパスしました。このときテスト実行率として正しいものはどれですか？',
        choices: ['80%', '85%', '95%', '100%'],
        correctAnswerIndex: 1,
        explanation: 'テスト実行率は「実行件数÷計画件数×100」で算出します。850÷1000×100=85%です。パス率は実行件数に対する合格件数の割合（800÷850≒94%）とは区別します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-070',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥密度',
        question: '5000行のコードに対して25件の欠陥が発見されました。欠陥密度（KLOC当たりの欠陥数）として正しいものはどれですか？',
        choices: ['0.5件/KLOC', '5件/KLOC', '25件/KLOC', '200件/KLOC'],
        correctAnswerIndex: 1,
        explanation: '欠陥密度はKLOC（1000行）当たりの欠陥数で表します。25件÷5（KLOC）＝5件/KLOCです。この指標でモジュール間の品質水準を比較したり、過去リリースと対比して品質傾向を分析できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-071',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト効率（歩留まり）',
        question: 'テストで発見した欠陥が40件、本番リリース後にユーザーが報告した欠陥が10件でした。このときのテスト欠陥検出率（歩留まり）として正しいものはどれですか？',
        choices: ['25%', '40%', '75%', '80%'],
        correctAnswerIndex: 3,
        explanation: '欠陥検出率（DDE）＝テストで発見した欠陥数÷（テストで発見した欠陥数＋本番で発見した欠陥数）×100です。40÷（40＋10）×100＝80%となり、テストがどれだけ欠陥を事前に捕捉できたかを示します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-072',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト完了基準（DoD）',
        question: 'スプリントのテスト完了基準（Definition of Done）として最も適切な記述はどれですか？',
        choices: ['全テストケースの実行が完了した時点', '全テストケースが実行済みで、重大度High以上の未解決欠陥がゼロであり、コードカバレッジが80%以上である', 'テスト実行に割り当てられた時間が終了した時点', '担当テスト担当者が完了と判断した時点'],
        correctAnswerIndex: 1,
        explanation: 'DoDは測定可能な基準を複数組み合わせることで完了を客観的に判断できます。実行率・欠陥残存状況・カバレッジなどを基準に設定することで、品質を担保しつつリリース判断の属人化を防げます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-073',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト見積もり（工数見積もり）',
        question: 'ECサイトのリニューアルプロジェクトで、テスト工数を見積もる際にQAリーダーが最初に確認すべき情報として最も適切なものはどれですか？',
        choices: ['開発チームの残業可能時間', 'テスト対象の機能数・複雑度・過去の欠陥密度', '使用するテスト管理ツールのライセンス費用', 'テスターの年齢と経験年数のみ'],
        correctAnswerIndex: 1,
        explanation: 'テスト工数見積もりには機能の規模と複雑度、過去プロジェクトの欠陥密度などの実績データが基礎情報として必要です。感覚や属人的な情報だけでは精度が下がります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-074',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト管理ツール（テスト計画・追跡）',
        question: 'テスト管理ツールを導入する主な目的として最も適切なものはどれですか？',
        choices: ['テストケースの自動実行を保証する', 'テスト進捗・実行結果・欠陥数を一元管理して可視化する', '開発者のコーディング速度を向上させる', 'テスト担当者の勤怠を記録する'],
        correctAnswerIndex: 1,
        explanation: 'テスト管理ツールはテストケース、実行状況、欠陥情報を一か所で管理し、プロジェクト関係者が進捗や品質状況をリアルタイムで把握できるようにする目的で使います。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-075',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト結果の分析',
        question: 'テスト実行後にパス率が95%でも、残り5%の失敗テストをそのままリリースすべきか判断するとき、最も重要な追加情報はどれですか？',
        choices: ['失敗テストの実行にかかった時間', '失敗テストが対象とする機能の重要度とリスク', 'テスト担当者の名前', 'テストツールのバージョン番号'],
        correctAnswerIndex: 1,
        explanation: 'パス率だけでなく、失敗しているテストがカバーする機能のビジネス影響やリスクを評価することで、リリース可否の意思決定に必要な情報が得られます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-076',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト報告書の読み方',
        question: '週次テストサマリーレポートを受け取ったプロジェクトマネージャーが、リリース判断に使うべき指標として最も適切なものはどれですか？',
        choices: ['テスト担当者が使った椅子の種類', '未解決の重大欠陥数とテストカバレッジの推移', 'テストケースのフォントサイズ', '過去プロジェクトの報告書の件数'],
        correctAnswerIndex: 1,
        explanation: 'テスト報告書では未解決欠陥の件数・重大度の推移とカバレッジの変化を読むことで、製品の現在のリスクレベルとリリース可否判断ができます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-077',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '品質ゲートと基準',
        question: 'スプリントレビュー前にチームが設定した品質ゲートとして最も典型的なものはどれですか？',
        choices: ['開発者全員がコーヒーを飲み終えたこと', '重大度「高」の未解決欠陥がゼロであること', 'テストケース数が偶数であること', '会議室が予約されていること'],
        correctAnswerIndex: 1,
        explanation: '品質ゲートとは次のフェーズへ進む前に満たすべき定量的・定性的な条件のことです。代表例は重大・致命的欠陥の未解決件数がゼロなどです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-078',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'バグトリアージ',
        question: '報告された欠陥が10件溜まった。限られた修正リソースの中でトリアージ会議が決めるべき内容として最も適切なものはどれですか？',
        choices: ['欠陥を発見した日付の古い順に全件修正する', '各欠陥の重大度・優先度を評価し、今スプリントで修正するものを選ぶ', 'テスター全員で欠陥を均等に割り振る', '欠陥の件数が多いファイルを削除する'],
        correctAnswerIndex: 1,
        explanation: 'バグトリアージとはリソースに対して欠陥の対応優先順位を決める活動です。重大度とビジネス優先度を組み合わせて修正対象を絞り込みます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-079',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥の重大度と優先度',
        question: '決済ページのUIボタンの色が仕様と異なる欠陥が報告された。重大度と優先度の組み合わせとして最も現実的なものはどれですか？',
        choices: ['重大度：高、優先度：高', '重大度：低、優先度：高', '重大度：低、優先度：低', '重大度：高、優先度：低'],
        correctAnswerIndex: 2,
        explanation: 'ボタン色のズレはシステムの機能に影響しないため重大度は低です。また業務への影響も小さいため優先度も低になりやすいです。ただしブランドガイドライン次第で優先度が上がることもあります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-080',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥の再現性と報告精度',
        question: 'テスト担当者が「たまにクラッシュする」とだけ報告した欠陥票を受け取った開発者が最初に要求すべき情報はどれですか？',
        choices: ['テスト担当者の好きな食べ物', '再現手順・環境情報・ログと再現率', 'クラッシュが発生した曜日のみ', 'プロジェクトの予算情報'],
        correctAnswerIndex: 1,
        explanation: '欠陥を修正するには再現できることが大前提です。具体的な操作手順、OSやブラウザのバージョン、エラーログがないと原因を特定できません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-081',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト組織とチーム構成',
        question: '独立したQAチームを設置する主なメリットとして最も適切なものはどれですか？',
        choices: ['開発者が一切テストをしなくてよくなる', '開発チームとは異なる視点で客観的に評価できる', '全欠陥を開発前に発見できるようになる', '顧客への報告が不要になる'],
        correctAnswerIndex: 1,
        explanation: '独立したQAチームは、実装した本人の思い込みや確証バイアスを排除し、外部視点でシステムを評価できます。ただし完全な欠陥除去を保証するわけではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-082',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'チーム内のテスト役割分担',
        question: 'スクラムチームで新機能を実装するとき、開発者とQAエンジニアが協力する場面として最も適切なものはどれですか？',
        choices: ['開発者が全テストを担当し、QAは不要', 'QAがテスト戦略を立案し、開発者がユニットテストを書きながら互いにレビューする', 'QAが要件を決めて開発者に指示するだけ', 'テストは全員が無作為に実施する'],
        correctAnswerIndex: 1,
        explanation: 'スクラムでは開発者がユニットテストを担当し、QAがシステム全体の戦略・受け入れテストを担当するなど、役割を補完し合うことで品質を高めます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-083',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '開発者テストとQAテストの違い',
        question: '開発者が行うテストとQAエンジニアが行うテストの典型的な違いとして最も適切なものはどれですか？',
        choices: ['開発者テストはシステム全体のE2Eテストを中心とし、QAテストはユニットテストだけ行う', '開発者テストは自分が書いたコードの正常動作確認、QAテストはユーザー視点での網羅的な検証', '両者まったく同じ内容で実施される', 'QAテストはコードを一切読まずに行う'],
        correctAnswerIndex: 1,
        explanation: '開発者テストは実装が仕様通りか検証するホワイトボックス的な確認が多く、QAテストは外部視点での機能・非機能・エッジケースまで含む広範な検証が主体です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-084',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ピアレビューの種類（インスペクション・ウォークスルー）',
        question: '設計書のレビューを行う際、著者が参加者に内容を説明しながら進める形式のレビューはどれですか？',
        choices: ['インスペクション', 'ウォークスルー', 'ペアプログラミング', 'コードカバレッジ測定'],
        correctAnswerIndex: 1,
        explanation: 'ウォークスルーは著者自身がドキュメントの内容を説明し、参加者が質問や意見を出す形式です。インスペクションは役割分担と形式的な欠陥ログ記録が特徴です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-085',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '要件レビューで見つかる問題',
        question: '要件レビューで発見できる問題として最も適切なものはどれですか？',
        choices: ['実装コードの構文エラー', '要件の曖昧さ・矛盾・欠落', 'データベースのパフォーマンス劣化', 'ネットワーク遅延の増加'],
        correctAnswerIndex: 1,
        explanation: '要件レビューの主な目的は「この仕様は誰が読んでも同じ意味に取れるか」「条件が抜けていないか」「他の要件と矛盾しないか」を確認することです。コードの問題は対象外です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-086',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '設計レビューで見つかる問題',
        question: 'アーキテクチャ設計のレビューで発見が期待される問題として最も適切なものはどれですか？',
        choices: ['タイポ（スペルミス）', 'モジュール間の依存関係の循環や単一障害点', '画面のフォントサイズ', 'テストケースの番号重複'],
        correctAnswerIndex: 1,
        explanation: '設計レビューでは依存関係の循環、不適切な責務分割、性能ボトルネックになりえる構造など、実装前に修正コストが低いうちに発見できる構造的問題を探します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-087',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'コードレビューで見つかる問題',
        question: 'コードレビューで発見しやすい問題として最も適切なものはどれですか？',
        choices: ['ユーザーインタビューの漏れ', '未使用変数・エラーハンドリング漏れ・セキュリティホール', '要件定義書の誤字', 'リリース日程の遅れ'],
        correctAnswerIndex: 1,
        explanation: 'コードレビューではコーディング規約違反、未使用変数、例外処理の漏れ、SQLインジェクションなどのセキュリティ問題を発見できます。要件や計画の問題は対象外です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-088',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '静的解析ツール（lintなど）',
        question: 'ESLintのような静的解析ツールを使う主な目的として最も適切なものはどれですか？',
        choices: ['コードを実行してUIの見た目を確認する', 'コードを実行せずに構文エラーや規約違反を検出する', 'データベースのクエリ実行計画を最適化する', 'テストケースを自動生成する'],
        correctAnswerIndex: 1,
        explanation: '静的解析ツールはコードを実行しないまま構文エラー、未使用変数、命名規約違反などを検出します。早期発見により修正コストを下げる効果があります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-089',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストドキュメントの種類',
        question: 'テスト計画書に記載する内容として最も適切なものはどれですか？',
        choices: ['個々のテストケースの入力値と期待結果', 'テストスコープ・アプローチ・スケジュール・リスク', '各欠陥の修正担当者名', 'ソースコードの行数'],
        correctAnswerIndex: 1,
        explanation: 'テスト計画書にはテストの範囲、採用する手法、スケジュール、必要なリソース、想定リスクなど全体方針を記載します。個々のケースの詳細はテスト仕様書や手順書に記載します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-090',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'トレーサビリティ（要件とテストの対応）',
        question: 'トレーサビリティマトリクスを作成する主な目的として最も適切なものはどれですか？',
        choices: ['テスト担当者のスキルを評価するため', 'どの要件がテストでカバーされているか・されていないかを一覧で確認するため', 'テストの実行時間を短縮するため', '欠陥の自動修正を行うため'],
        correctAnswerIndex: 1,
        explanation: 'トレーサビリティマトリクスで要件とテストケースを紐付けることで、テストが漏れている要件や、逆に要件がない冗長なテストを素早く特定できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-091',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テストベース（仕様書・モデルなど）',
        question: 'テストケースを設計するときに「テストベース」として使えるものとして最も適切なものはどれですか？',
        choices: ['開発者のプログラミング経験年数', '機能仕様書・UMLモデル・ユーザーストーリー', 'テストツールのライセンス契約書', 'オフィスの座席配置図'],
        correctAnswerIndex: 1,
        explanation: 'テストベースはテストケースを導出するための根拠となる情報全般を指します。機能仕様書、設計書、モデル図、ユーザーストーリーなどが該当します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-092',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストオラクルのタイプ',
        question: '既存の旧システムの動作結果を新システムのテスト期待値として使う場合、このテストオラクルの種類として最も適切なものはどれですか？',
        choices: ['暗黙的オラクル', '参照オラクル（リファレンス実装）', '無オラクル', 'ランダムオラクル'],
        correctAnswerIndex: 1,
        explanation: '旧システムの出力を新システムの期待値として使う手法は参照オラクルと呼ばれます。移行プロジェクトやリプレイスで特によく使われます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-093',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '等価クラス分割の応用',
        question: '会員ランクが「一般（0〜999ポイント）」「シルバー（1000〜4999ポイント）」「ゴールド（5000ポイント以上）」に分かれるシステムで、等価クラス分割を適切に行った場合のテストケース数（有効クラスのみ）として最も適切なものはどれですか？',
        choices: ['1件', '2件', '3件', '6件'],
        correctAnswerIndex: 2,
        explanation: '3つのランクがそれぞれ1つの等価クラスを形成するため、有効クラスの代表値は各ランクから1件ずつで計3件です。境界値や無効クラスは別途追加します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-094',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '境界値分析の応用（3点法）',
        question: '割引率が「購入金額1万円以上で10%引き」と定義されている。3点法（境界値・境界値−1・境界値+1）で確認すべき値の組み合わせはどれですか？',
        choices: ['5000円、8000円、12000円', '9999円、10000円、10001円', '1円、5000円、9999円', '10000円、20000円、30000円'],
        correctAnswerIndex: 1,
        explanation: '3点法では境界値10000円とその直前9999円・直後10001円を確認します。境界付近の比較演算子ミスを効率よく発見できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-095',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '決定表の作成手順',
        question: '決定表を作成する際の正しい手順として最も適切なものはどれですか？',
        choices: ['まずテストを実行し、その後に条件を整理する', '条件と動作を列挙し、条件の組み合わせごとの動作を表に整理する', '動作だけを先に決めて後から条件を当てはめる', 'コードを先に書いてから条件を逆算する'],
        correctAnswerIndex: 1,
        explanation: '決定表は条件（入力値）と動作（出力・処理）を列挙し、全条件の組み合わせに対して期待動作を整理するものです。作成過程でロジックの矛盾や漏れを発見できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-096',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '状態遷移図の読み方',
        question: 'ユーザーアカウントが「未認証→認証済み→ロック」という状態遷移図がある。「ロック状態から認証済みへの矢印がない」場合に意味することとして最も適切なものはどれですか？',
        choices: ['ロック状態から直接認証済みへ移行できる', 'ロック状態から認証済みへの直接遷移は設計上存在しない', '認証済みからロックへの遷移が存在しない', '未認証状態が削除されている'],
        correctAnswerIndex: 1,
        explanation: '状態遷移図で矢印がない場合、その遷移は設計上存在しないことを意味します。ロックされた場合は管理者によるリセットなど別のパスが必要なことが読み取れます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-097',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '状態遷移テーブルの使い方',
        question: '状態遷移テーブルを使う主な利点として最も適切なものはどれですか？',
        choices: ['コードの自動生成ができる', '状態と遷移の全組み合わせを一覧化し、テストすべきケースの漏れを防ぐ', 'UIのデザインを確定できる', 'テスト実行時間を自動計測できる'],
        correctAnswerIndex: 1,
        explanation: '状態遷移テーブルは現在の状態×イベントの全組み合わせを表にすることで、テストしていない遷移や定義されていない組み合わせ（無効遷移）を発見しやすくします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-098',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ユースケースの主フローと代替フロー',
        question: '「商品購入」ユースケースの代替フローに含まれる内容として最も適切なものはどれですか？',
        choices: ['ユーザーが正常に商品を選択して決済する一連の流れ', '在庫切れ時にユーザーへ通知して処理を終了する流れ', 'システムの起動手順', 'テストケースの番号付けルール'],
        correctAnswerIndex: 1,
        explanation: '代替フローは主フロー（正常系）から分岐する例外や異常のケースを記述します。在庫切れ・決済失敗・タイムアウトなどが典型例です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-099',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '組み合わせテスト（直交表）',
        question: '3つの設定項目がそれぞれ3値を持つとき、全組み合わせは27通りになる。直交表を使う主な目的として最も適切なものはどれですか？',
        choices: ['全27通りを2倍に増やして網羅性を高める', '少ないテストケースで2因子間の組み合わせを網羅する', 'テストを1件だけで済ませる', '全組み合わせを網羅せず完全にランダムに選ぶ'],
        correctAnswerIndex: 1,
        explanation: '直交表を使うと全組み合わせ27件を大幅に削減しながら、どの2因子の組み合わせも最低1回は出現することを保証できます。効率と網羅性のバランスを取る手法です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-100',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '因果グラフ',
        question: '因果グラフをテスト設計に用いる主な目的として最も適切なものはどれですか？',
        choices: ['プログラムの実行速度を計測する', '入力条件と出力結果の論理的な因果関係を可視化し、決定表に変換する', 'テスト担当者の作業量を増やす', 'UIのレイアウトを決定する'],
        correctAnswerIndex: 1,
        explanation: '因果グラフは原因（入力条件）と結果（出力）の論理関係を図で表し、組み合わせテストに必要な決定表を導出するための手法です。論理的に重要な組み合わせを見落とさずに特定できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-101',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '経験ベーステスト技法まとめ',
        question: '経験ベーステスト技法の特徴として最も適切なものはどれですか？',
        choices: ['テスト担当者の経験や知識に依存しない体系的な手法', 'テスト担当者の経験や直感を活かして仕様には明示されない問題を探す', '全機能を等確率でテストする', '自動化ツールのみで実施できる'],
        correctAnswerIndex: 1,
        explanation: '経験ベーステスト技法はテスト担当者の過去の経験、類似システムへの知識、ドメイン理解を利用して、仕様書からは導けない問題を見つける手法群です。探索的テスト・エラー推測が代表例です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-102',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト技法の選択基準',
        question: '詳細な機能仕様書が存在し、条件の組み合わせが多い画面のテスト設計に最も適した技法はどれですか？',
        choices: ['探索的テストのみ', '決定表テスト', 'ランダムテスト', 'インタビューのみ'],
        correctAnswerIndex: 1,
        explanation: '条件の組み合わせが多く仕様書が整備されている場合は決定表テストが有効です。ロジックの全組み合わせを体系的に整理し、テスト漏れを防げます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-103',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '探索的テストのセッション管理',
        question: '探索的テストをセッションベースで実施するとき、各セッション開始前に決めるべき内容として最も適切なものはどれですか？',
        choices: ['テスターの昼食メニュー', 'テストチャーター（目的・対象・アプローチ）と時間枠', '過去の全欠陥の修正履歴', '今後1年の開発ロードマップ'],
        correctAnswerIndex: 1,
        explanation: 'セッションベース探索的テストでは各セッションの開始前にテストチャーターで「何を・どのように探るか」と時間枠を定義することで、結果の記録と振り返りが可能になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-104',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'クラウドテスト環境',
        question: 'クラウド上にテスト環境を構築する主なメリットとして最も適切なものはどれですか？',
        choices: ['物理サーバーの増設が不要で、需要に応じてリソースをスケールできる', 'テストが自動的に全合格になる', 'ネットワーク遅延がゼロになる', 'テスト担当者が不要になる'],
        correctAnswerIndex: 0,
        explanation: 'クラウド環境では負荷テスト時など一時的に大量のリソースが必要な場面でも、物理購入不要でスケールアウトできます。コスト効率と柔軟性が主なメリットです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-105',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '仮想化・コンテナとテスト',
        question: 'Dockerコンテナを使ってテスト環境を構築する主な利点として最も適切なものはどれですか？',
        choices: ['テストケースが自動で生成される', '環境の再現性が高く、テスト担当者が同一の条件でテストを繰り返せる', 'コードの品質が自動的に向上する', '欠陥が自動修正される'],
        correctAnswerIndex: 1,
        explanation: 'コンテナは依存関係・OSバージョン・設定を含む環境をイメージとして固定できます。「自分のPCでは動くが本番では動かない」問題を減らし、テストの再現性を高めます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-106',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'CI/CDパイプラインのテスト戦略',
        question: 'CI/CDパイプラインでプルリクエスト時に自動実行するテストとして最も適切なものはどれですか？',
        choices: ['手動の受け入れテストのみ', 'ユニットテストと結合テストをビルドごとに自動実行する', 'テストを全て省略してデプロイ速度を優先する', '本番環境の全データで負荷テストを実施する'],
        correctAnswerIndex: 1,
        explanation: 'CI/CDではプルリクエストのたびにユニットテストと結合テストを自動実行することで、コードの変更が既存機能を壊していないか素早くフィードバックを得られます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-107',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストデータ管理',
        question: '本番データをテスト環境にそのままコピーして使う場合に最も注意すべき問題はどれですか？',
        choices: ['テストケースの件数が増えすぎる', '個人情報や機密データの漏洩リスク', 'テスト実行が速くなりすぎる', 'テスト環境が起動しなくなる'],
        correctAnswerIndex: 1,
        explanation: '本番データにはユーザーの個人情報やクレジットカード情報が含まれることが多く、テスト環境へのコピーは情報漏洩リスクになります。マスキングや匿名化が必要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-108',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト環境のリセットと再現性',
        question: 'テスト実行のたびにデータが変化しないよう、テスト前にデータベースをリセットする仕組みを入れる主な理由として最も適切なものはどれですか？',
        choices: ['テストの実行速度を遅くするため', 'テストが独立して実行でき、前回の結果に影響されないようにするため', 'ログを自動的に圧縮するため', 'テスト担当者の作業工数を増やすため'],
        correctAnswerIndex: 1,
        explanation: 'テスト環境を毎回既知の初期状態に戻すことで、テストが互いに干渉せず独立して実行でき、失敗の原因特定が容易になります。再現性の確保は信頼性の高いテスト結果の前提条件です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-109',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの費用対効果',
        question: 'テスト工程に投資する費用対効果を高めるための考え方として最も適切なものはどれですか？',
        choices: ['できるだけ多くのテストケースを作成する', 'リスクが高い機能に重点的にテストを集中させる', 'テストはリリース直前の1日だけ行う', '全機能を均等な時間でテストする'],
        correctAnswerIndex: 1,
        explanation: 'テストのROIを高めるにはリスクベースドアプローチで、障害が起きたときの影響が大きい機能や複雑な機能にテスト工数を優先投入することが効果的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-110',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '品質コスト（予防・評価・失敗）',
        question: 'ソフトウェアにおける「内部失敗コスト」の例として最も適切なものはどれですか？',
        choices: ['要件レビューにかかる費用', 'リリース前のQAテスト実施費用', 'リリース前に発見された欠陥の修正費用', '本番障害でユーザーが受けた損害への補償費用'],
        correctAnswerIndex: 2,
        explanation: '内部失敗コストはリリース前に発見された欠陥の手直し・再テスト費用です。外部失敗コストは本番後の問題対応費用、評価コストはテスト実施費用、予防コストはレビュー・教育費用に分類されます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-111',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リリース後の品質モニタリング',
        question: 'リリース後の品質をモニタリングする手段として最も適切なものはどれですか？',
        choices: ['リリース前のテスト結果のみを参照する', 'エラーログ・クラッシュレート・ユーザーからの不具合報告を継続して収集・分析する', 'リリース後はテストを一切行わない', '開発者のコミット頻度だけを測定する'],
        correctAnswerIndex: 1,
        explanation: 'リリース後はアプリケーションのエラーログ、クラッシュレート、レイテンシ、ユーザーサポートへの問い合わせなどを継続的に収集・分析することで、潜在的な品質劣化をいち早く検知できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-112',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '本番障害からのフィードバック',
        question: '本番障害が発生した後にQAプロセス改善として最も適切な対応はどれですか？',
        choices: ['障害発生の責任を担当者個人に問う', '障害の原因を分析し、同種の問題を検知できるテストケースを追加する', 'テスト工数を削減して速度を優先する', '障害報告書を書かずに口頭で共有するだけにする'],
        correctAnswerIndex: 1,
        explanation: '本番障害は既存テストセットの穴を示しています。根本原因を分析し、同じパターンの問題を今後早期に発見できるリグレッションテストを追加することが品質プロセスの改善につながります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-113',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '安全性テスト（フェールセーフ）',
        question: '工場の制御システムで、ネットワーク断線が発生した際に機械が自動停止する設計をテストしている。最も適切なテストアプローチはどれか。',
        choices: ['ネットワークケーブルを実際に抜いて機械が停止することを確認する', '仕様書に停止処理が記載されていることを確認するだけにする', '正常系のみテストして異常系は省略する', 'ネットワーク断線はまれなので優先度を下げる'],
        correctAnswerIndex: 0,
        explanation: 'フェールセーフはシステムが安全側に倒れる設計です。実際に障害を発生させてシステムが意図通り安全状態へ遷移することを実機で確認することが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-114',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '回復性テスト（障害復旧確認）',
        question: 'ECサイトのサーバーが突然クラッシュした後、自動再起動して処理を再開するまでの時間を確認するテストをしている。このテストで主に検証しているものはどれか。',
        choices: ['回復時間目標（RTO）が満たされているか', 'ピーク時の最大同時接続数', '画面のUIデザインに崩れがないか', '決済機能の計算ロジック'],
        correctAnswerIndex: 0,
        explanation: '回復性テストでは障害発生からシステムが正常状態に戻るまでの時間（RTO）が要件を満たすかどうかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-115',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'バックアップ・リストアのテスト',
        question: '顧客管理システムで毎晩バックアップを取得している。バックアップの有効性を確認する最も重要な作業はどれか。',
        choices: ['バックアップの実行ログだけを目視確認する', '別の環境にリストアしてデータが正しく復元できることを検証する', 'バックアップファイルのサイズが前回と同じか確認する', 'バックアップ開始時刻が定刻通りかだけを確認する'],
        correctAnswerIndex: 1,
        explanation: 'バックアップが存在してもリストアできなければ意味がありません。実際に別環境へ復元し、データの整合性と業務継続に必要な情報が揃っているかを確認することが最重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-116',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '設定変更テスト',
        question: 'Webアプリで「セッションタイムアウト時間」を設定画面から変更できる。テスト担当者が実施すべきテストとして最も適切なものはどれか。',
        choices: ['設定値を変更した後に実際のタイムアウト動作が変更値通りになることを確認する', '設定画面のUIデザインを確認するだけにする', '設定画面が表示されることだけを確認する', '変更前の値と変更後の値が異なることだけを確認する'],
        correctAnswerIndex: 0,
        explanation: '設定変更テストでは、変更した設定値が実際の動作に反映されているかを確認することが核心です。UIの見た目だけでなく、機能の振る舞いへの影響を検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-117',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ドキュメントのテスト（マニュアル検証）',
        question: '新機能リリースに合わせてユーザーマニュアルを更新した。マニュアルのテストとして最も重要な確認事項はどれか。',
        choices: ['マニュアルのページ数が前回より増えていること', 'マニュアルの記述通りに操作して実際に動作することを確認する', 'フォントと余白が統一されていること', 'PDFファイルが開けること'],
        correctAnswerIndex: 1,
        explanation: 'マニュアルのテストでは、記載された手順通りに操作して製品が正しく動くことを検証します。手順の正確性と機能との一致が最優先です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-118',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'エラーメッセージの品質確認',
        question: 'ログイン画面でパスワードを間違えたときに「エラーが発生しました」とだけ表示される。このエラーメッセージの問題として最も適切な指摘はどれか。',
        choices: ['メッセージが短すぎるので長くすべきだ', 'ユーザーが次に何をすればよいか分からない不親切な表示だ', 'エラーメッセージは表示しない方がセキュリティ上良い', 'エラーの色が赤でないので問題だ'],
        correctAnswerIndex: 1,
        explanation: '良いエラーメッセージは何が起きたかだけでなく、次の行動（パスワードを再入力する、パスワードを忘れた場合はリンクを使うなど）をユーザーに示すことが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-119',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '多言語・文字コードのテスト',
        question: 'Webフォームに日本語の氏名を入力して保存し、再表示したら「???」と文字化けしていた。原因として最も疑うべきものはどれか。',
        choices: ['データベースのインデックスが不足している', '文字コードの不一致（例: UTF-8とShift-JIS混在）', 'ネットワーク帯域が不足している', 'CSSのフォント設定が誤っている'],
        correctAnswerIndex: 1,
        explanation: '文字化けは保存・通信・表示の各層で文字コードが統一されていない場合に発生します。特にUTF-8とShift-JIS、EUC-JPなどが混在するシステムでよく起きます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-120',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '日付・タイムゾーンのテスト',
        question: '日本（UTC+9）とニューヨーク（UTC-5）の両拠点に利用者がいる予約システムをテストしている。最も確認すべき観点はどれか。',
        choices: ['サーバーのOSバージョンが最新か', '各ユーザーのタイムゾーンで表示される予約日時が正しく変換されているか', 'データベースのテーブル数が適切か', 'ログイン画面のデザインが共通か'],
        correctAnswerIndex: 1,
        explanation: 'タイムゾーンをまたぐシステムでは、UTCで保存した日時をユーザーの現地時刻に正しく変換して表示しているか、予約の重複判定がタイムゾーンをまたいでも正確かを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-121',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '認証・認可のテスト',
        question: '社内システムで「一般ユーザー」と「管理者」の2種類のロールがある。認可テストとして最も重要な確認はどれか。',
        choices: ['管理者と一般ユーザーで同じURLにアクセスして、一般ユーザーが管理機能を操作できないことを確認する', 'どちらのロールもログインできることを確認する', 'パスワードが8文字以上であることを確認する', 'ログアウトボタンが表示されることを確認する'],
        correctAnswerIndex: 0,
        explanation: '認可テストでは権限のないユーザーが保護されたリソースにアクセスできないことを直接確認します。ロールごとの操作制限が正しく機能しているか検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-122',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'セッション管理のテスト',
        question: 'ログアウト操作後もブラウザの「戻る」ボタンで前のページが表示されてしまう問題を報告した。このテストで確認していた観点はどれか。',
        choices: ['セッション終了後にキャッシュや古いページへのアクセスが無効化されているか', 'ブラウザのバージョンが最新か', 'ネットワーク速度が十分か', 'ページのHTMLに構文エラーがないか'],
        correctAnswerIndex: 0,
        explanation: 'セッション管理テストでは、ログアウト後にセッションが完全に無効化されているかを確認します。キャッシュに残ったページが再表示される場合、認証済みコンテンツが第三者に見られるリスクがあります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-123',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '入力サニタイズ確認',
        question: '商品検索フォームに `<script>alert(1)</script>` を入力して送信したところ、画面にアラートが表示された。これはどのような問題か。',
        choices: ['XSS（クロスサイトスクリプティング）の脆弱性がある', 'パフォーマンスが低下している', 'データベース接続が切れている', 'レスポンシブデザインが崩れている'],
        correctAnswerIndex: 0,
        explanation: 'ユーザー入力のスクリプトタグがそのまま画面に出力されてしまうのはXSS脆弱性です。入力値はHTMLエスケープなどでサニタイズし、スクリプトとして実行されないよう処理する必要があります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-124',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ファイルアップロードのセキュリティテスト',
        question: 'プロフィール画像のアップロード機能をテストしている。セキュリティの観点で最も重要な確認事項はどれか。',
        choices: ['拡張子が「.exe」などの実行ファイルもアップロードできてしまわないかを確認する', '画像ファイルのアップロードボタンが表示されることだけを確認する', 'アップロード後にページが再読み込みされることを確認する', 'ファイル名が変更されないことを確認する'],
        correctAnswerIndex: 0,
        explanation: 'ファイルアップロード機能では許可していないファイル種別が送信できないか確認します。ファイルタイプの検証が不十分だとサーバー上で悪意あるコードが実行される恐れがあります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-125',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'メール送信テストの注意点',
        question: 'ユーザー登録後に確認メールを送信する機能をテストする際の注意点として最も適切なものはどれか。',
        choices: ['本番の顧客メールアドレスを使ってテストメールを大量送信する', 'テスト専用のメールアドレスや受信確認ツールを使い、本番メールアドレスへの誤送信を防ぐ', 'メールの件名だけ確認して本文は省略する', 'テスト環境ではメール送信を一切確認しない'],
        correctAnswerIndex: 1,
        explanation: 'メール送信テストでは実際の顧客へ誤送信しないよう、テスト専用アドレスやMailHogなどのダミーSMTPサーバーを使います。本文・件名・宛先・リンク・文字化けの確認も必要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-126',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '外部連携APIのテスト',
        question: '外部の天気予報APIと連携するアプリをテストしている。外部APIが利用できないときのテストとして最も適切なアプローチはどれか。',
        choices: ['外部APIが常に利用可能であることを前提にテストする', 'モックサーバーを使って外部API障害時のアプリの挙動を確認する', '外部APIのテストはAPIプロバイダーの責任なので省略する', '外部API連携機能のテストはリリース後に行う'],
        correctAnswerIndex: 1,
        explanation: '外部APIのテストではモックやスタブを使い、APIがエラーを返したりタイムアウトした場合にアプリが適切にエラー処理できるかを確認します。実際の外部サービスに依存するとテストが不安定になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-127',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '非同期処理のテスト',
        question: '注文確定後にバックグラウンドで在庫更新を行う非同期処理をテストしている。最も重要な確認事項はどれか。',
        choices: ['注文確定ボタンの色が正しいか', '注文確定後、在庫数が正しく更新されるタイミングと最終的な整合性を確認する', '非同期処理は内部実装なのでテスト不要とする', 'バックエンドのコード行数が適切か'],
        correctAnswerIndex: 1,
        explanation: '非同期処理のテストでは処理が完了するまでの待機、処理失敗時のリトライ、最終的なデータの整合性を確認します。処理タイミングの誤りはデータ不整合を生むため重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-128',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'キャッシュのテスト',
        question: '商品価格を更新した直後に商品ページを確認したら古い価格が表示されていた。テスト担当者が確認すべき内容として最も適切なものはどれか。',
        choices: ['価格入力フォームのデザインを確認する', 'キャッシュが適切に無効化されて最新データが表示されているかを確認する', 'ネットワーク速度を測定する', 'データベースのバージョンを確認する'],
        correctAnswerIndex: 1,
        explanation: '更新後も古いデータが表示されるのはキャッシュの問題である可能性が高いです。更新操作後にキャッシュが正しくクリアまたは更新されて最新の値が表示されることを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-129',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'データベース整合性のテスト',
        question: '受注テーブルに存在しない顧客IDが参照されているレコードが見つかった。このような問題を防ぐテストの観点として最も適切なものはどれか。',
        choices: ['外部キー制約が正しく設定されており、孤立したレコードが作成されないかを確認する', 'データベースのクエリ実行速度を測定する', 'テーブルの列数が仕様書と一致するかを確認する', 'データベースへの同時接続数を確認する'],
        correctAnswerIndex: 0,
        explanation: 'データベース整合性テストでは外部キー制約や参照整合性が正しく機能しているかを確認します。孤立したレコードはデータの矛盾を生み、集計や帳票に誤りをもたらします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-130',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'トランザクション・ロールバックのテスト',
        question: '振込処理でA口座から引き落としはできたが、B口座への入金処理でエラーが発生した。正しい設計であれば次のどの挙動が期待されるか。',
        choices: ['A口座の引き落としだけが確定してそのまま終了する', 'A口座の引き落としもロールバックされ、残高が元の状態に戻る', 'B口座への入金だけ後で自動的に再試行される', '操作はなかったことにしてエラーログも残さない'],
        correctAnswerIndex: 1,
        explanation: 'トランザクションはすべての処理が成功したときだけコミットし、一つでも失敗したら全体をロールバックするのが原則です。部分的な更新はデータ不整合を引き起こします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-131',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'バッチ処理のテスト',
        question: '毎月1日に前月分の請求データを一括生成するバッチ処理をテストしている。テストとして最も重要な確認はどれか。',
        choices: ['バッチが定時に起動したかだけをログで確認する', '生成された請求データの件数・金額が手計算や別集計と一致するかを検証する', 'バッチ処理のプログラムの行数を数える', 'バッチ実行中にCPU使用率が100%にならないか確認する'],
        correctAnswerIndex: 1,
        explanation: 'バッチ処理テストでは出力結果の正確性の検証が最重要です。期待する件数と金額が一致するかを独立した集計方法と比較し、処理漏れや重複がないことを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-132',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '排他制御・競合のテスト',
        question: 'チケット残り1枚の状態で2人のユーザーが同時に購入操作をした場合のテスト結果として、正しい実装であれば何が期待されるか。',
        choices: ['両方のユーザーが購入に成功してチケットが2枚販売されてしまう', '一方だけが購入成功し、もう一方には在庫切れエラーが返る', '両方のユーザーにエラーが返りどちらも購入できない', '処理がフリーズしてサーバーが応答しなくなる'],
        correctAnswerIndex: 1,
        explanation: '排他制御が正しく実装されていれば、同時リクエストでも在庫数を超えた販売は発生しません。楽観的ロックや悲観的ロックにより先勝ちした一方だけが成功し、もう一方には適切なエラーが返ります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-133',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'メモリリーク確認',
        question: 'アプリを長時間使い続けると動作が遅くなると報告があった。メモリリークを調査するために最初に行うべき確認として適切なものはどれか。',
        choices: ['アプリのフォントサイズを変更する', '操作を繰り返しながらメモリ使用量を継続監視し、増え続けていないかを確認する', 'データベースの列数を削減する', 'ログイン画面のデザインを見直す'],
        correctAnswerIndex: 1,
        explanation: 'メモリリークの特徴は、使用を続けるほどメモリ使用量が増加し続けることです。プロファイラやタスクマネージャでメモリ推移を時系列で観察し、解放されずに増加し続けるかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-134',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ログ出力のテスト',
        question: '本番障害が発生したが、ログには「エラーが起きました」とだけ記録されており原因追跡ができなかった。ログテストで確認すべきだった内容として最も適切なものはどれか。',
        choices: ['ログファイルのサイズが一定以下であること', 'エラー発生時にスタックトレース・発生箇所・関連する入力値などが記録されること', 'ログの文字数が一定以上であること', 'ログが毎秒1件以上出力されること'],
        correctAnswerIndex: 1,
        explanation: '障害調査に役立つログには発生日時・場所・エラーの種類・関連データ・スタックトレースが含まれる必要があります。漠然としたメッセージだけでは原因特定ができません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-135',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'モバイルアプリのテスト特有の観点',
        question: 'スマートフォンアプリのテストでPCブラウザでは確認できない観点として、最も適切なものはどれか。',
        choices: ['文字列のソートロジック', '電話の着信割り込みが来たときにアプリが正しく動作するか', 'HTTPステータスコードの返却値', 'データベースのインデックス効率'],
        correctAnswerIndex: 1,
        explanation: 'モバイルアプリ特有の観点には電話・通知による割り込み、バッテリー低下、バックグラウンド移行・復帰、画面回転などがあります。これらはPCブラウザでは発生しないシナリオです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-136',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'レスポンシブデザインのテスト',
        question: 'スマートフォンで表示すると商品一覧の画像とテキストが重なってしまった。この不具合を早期に発見する方法として最も適切なものはどれか。',
        choices: ['コードレビューだけで画面確認は省略する', 'ブラウザの開発者ツールで複数の画面幅をシミュレートしながらレイアウトを確認する', 'サーバーのメモリ使用量を確認する', 'データベースのレコード数を確認する'],
        correctAnswerIndex: 1,
        explanation: 'レスポンシブデザインテストでは開発者ツールのデバイスシミュレーターや実機を使い、さまざまな画面幅でレイアウトが崩れないかを確認します。ブレークポイント付近を重点確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-137',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'デバイス機能のテスト',
        question: 'QRコードをカメラで読み取るモバイルアプリをテストする際に、必ず実機でテストすべき理由として最も適切なものはどれか。',
        choices: ['実機の方がビルドが速いから', 'シミュレーターでは実際のカメラハードウェアの動作や照明条件の影響を再現できないから', 'サーバーサイドのテストには実機が必要だから', 'UI配置の確認は実機でしかできないから'],
        correctAnswerIndex: 1,
        explanation: 'カメラ・マイク・GPS・加速度センサーなどのデバイス機能はシミュレーターでは完全に再現できません。実際の照明条件や異なる機種のカメラ性能など、実機でのみ確認できる観点があります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-138',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'オフライン動作のテスト',
        question: 'メモアプリでオフライン中に入力した内容が、ネットワーク復帰後にサーバーと同期されることをテストしている。確認すべき観点として最も重要なものはどれか。',
        choices: ['オフライン中の画面のフォントが正しいか', 'オフライン入力データが同期時に失われたり重複したりしないか', 'ネットワーク接続中のレスポンス速度', '画面の色数がデザイン仕様と一致するか'],
        correctAnswerIndex: 1,
        explanation: 'オフライン機能のテストではデータが失われずに同期されること、同じデータが重複して登録されないこと、競合が発生した場合の解決策が正しいことを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-139',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'プッシュ通知のテスト',
        question: 'プッシュ通知機能をテストする際の確認事項として、最も見落とされやすい観点はどれか。',
        choices: ['アプリアイコンのデザインが適切か', 'アプリがバックグラウンド状態のときやOSの通知設定をオフにしたときの挙動', 'サーバーのCPU使用率', 'データベースのテーブル設計'],
        correctAnswerIndex: 1,
        explanation: 'プッシュ通知テストではフォアグラウンド・バックグラウンド・通知拒否の各状態、通知タップ時の画面遷移、同じ通知の重複送信がないかなど、状態による挙動の違いを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-140',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'アプリ更新・バージョンアップのテスト',
        question: 'アプリを旧バージョンからアップデートした際に、以前保存していたデータが消えてしまった。これはどのテストで検出すべきだったか。',
        choices: ['新規インストール時のみのテスト', 'アップデート（移行）テストで既存データの引き継ぎを確認するテスト', 'ネットワーク速度のテスト', 'UIのカラーテスト'],
        correctAnswerIndex: 1,
        explanation: 'バージョンアップテストでは新規インストールだけでなく旧バージョンからのアップグレードシナリオも検証します。データ移行・スキーマ変更による既存データへの影響を確認することが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-141',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの再利用性',
        question: 'テストケースを再利用しやすくするための工夫として、最も効果的なものはどれか。',
        choices: ['テスト担当者名を必ずコメントに入れる', '前提条件・手順・期待結果を明確に分けて記述し、特定の環境や個人に依存しない形にする', 'テスト手順をできるだけ長く詳細に書く', 'テスト実施日をタイトルに含める'],
        correctAnswerIndex: 1,
        explanation: '再利用可能なテストケースは環境や担当者に依存せず、前提条件が明確に定義されています。共通の初期化手順をモジュール化し、テストデータを外部から供給できる構造にすることも重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-142',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストスイートの管理',
        question: 'テストスイートを適切に管理する目的として、最も適切なものはどれか。',
        choices: ['テストケースの総数を最大化するため', '重複を排除し網羅性を維持しながらテスト実行の優先付けと選択ができるようにするため', 'テスト担当者の作業量を均等に分配するためだけ', '仕様書のページ数に合わせてケース数を揃えるため'],
        correctAnswerIndex: 1,
        explanation: 'テストスイート管理ではケースの重複排除、リスク別の優先順位付け、回帰テスト範囲の選択が目的です。管理が不十分だと古いケースや冗長なケースが蓄積し、実行コストが増大します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-143',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの負債',
        question: '「テストの負債」として問題になる状況として、最も適切なものはどれか。',
        choices: ['テストが多すぎてカバレッジが100%を超えている', '仕様変更に追従しないまま放置された古いテストが蓄積し、メンテナンスコストが増大している', 'テストが高速に実行されすぎる', 'テストの実行回数が多い'],
        correctAnswerIndex: 1,
        explanation: 'テストの負債とは仕様変更後も修正されなかったテストや、重複・陳腐化したテストが積み重なった状態です。偽陽性・偽陰性が増え、修正コストが膨らみます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-144',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストコードのリファクタリング',
        question: 'テストコードのリファクタリングを行うタイミングとして最も適切なものはどれか。',
        choices: ['テストが失敗したときだけリファクタリングする', '機能実装のリファクタリングとは別に、テストも定期的に可読性・重複除去・保守性を改善する', 'リリース直前だけにリファクタリングする', 'テストコードはリファクタリングしてはならない'],
        correctAnswerIndex: 1,
        explanation: 'テストコードも製品コードと同様に保守対象です。定期的に重複除去・命名改善・共通ヘルパー抽出を行うことで、長期的な保守コストを下げ、新しいテストを追加しやすくします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-145',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト担当者のスキルアップ',
        question: 'テスト担当者がスキルアップするために継続的に行うべき活動として、最も適切なものはどれか。',
        choices: ['同じテスト手法だけを繰り返し使う', '振り返りで自分の見逃しパターンを分析し、新しいテスト技法や業界事例を積極的に学ぶ', '他のメンバーのレビューを受けない', 'テストドキュメントを作成しない'],
        correctAnswerIndex: 1,
        explanation: 'テスト担当者のスキルアップには、自分の弱点を振り返り・分析する習慣、テスト技法の継続学習、他者のレビューやカンファレンス・書籍からの知識吸収が有効です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-146',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'バグ報告の書き方実践',
        question: '不具合報告で「ボタンが動きません」とだけ記載されていた。この報告の問題として最も重要なものはどれか。',
        choices: ['報告が短すぎて文字数が足りない', '再現手順・環境・期待結果・実際の結果が不足しており開発者が再現できない', '句読点の使い方が適切でない', 'バグのIDが記載されていない'],
        correctAnswerIndex: 1,
        explanation: '有効なバグ報告には発生環境、再現手順、期待結果、実際の結果、添付資料が必要です。情報が不足すると開発者が再現できずに解決が遅れます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-147',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'スクリーンショットと動画の活用',
        question: '断続的に発生する不具合を報告するとき、スクリーンショットより動画記録が有効な理由として最も適切なものはどれか。',
        choices: ['動画の方がファイルサイズが小さいから', '一時的な状態変化や操作の流れを時系列で記録でき、再現の手がかりになるから', '動画の方が作成が簡単だから', 'スクリーンショットはOSによって撮影できないから'],
        correctAnswerIndex: 1,
        explanation: '断続的なバグは特定の操作順序や状態遷移で発生することが多く、動画ならその流れを記録できます。開発者が同じ操作を再現しやすくなり、デバッグ時間を短縮できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-148',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト環境と本番環境の差異管理',
        question: 'テスト環境で問題なかった機能が本番でのみ障害を起こした。この原因として最も疑うべき差異はどれか。',
        choices: ['テスト担当者と本番運用者の氏名が異なる', 'テスト環境と本番環境でOSバージョン・設定・データ量・外部連携先などが異なっていた', 'テストケースの数が本番の処理数と異なる', 'ログイン画面のデザインが環境によって異なる'],
        correctAnswerIndex: 1,
        explanation: '「テスト環境では再現しない」問題の主な原因はOSやミドルウェアのバージョン差、環境変数の設定差、テストと本番のデータ量の差、外部連携先の違いなどです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-149',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'カナリアリリースとテスト',
        question: 'カナリアリリースを採用する主な目的として、最も適切なものはどれか。',
        choices: ['すべてのユーザーに同時に新機能を届けるため', '一部のユーザーに新バージョンを先行展開して本番での問題を早期検出し、影響範囲を限定するため', 'テスト工数を完全になくすため', 'リリースの作業時間を短縮するだけのため'],
        correctAnswerIndex: 1,
        explanation: 'カナリアリリースでは新バージョンをごく一部のユーザーに先行展開し、エラー率やパフォーマンスを監視します。問題があれば全展開前に切り戻せるため、障害の影響範囲を最小化できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-150',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'フィーチャーフラグとテスト',
        question: 'フィーチャーフラグを使って新機能をリリースする場合、テスト担当者が追加で確認すべき観点として最も適切なものはどれか。',
        choices: ['フラグのコードが何行あるかを数える', 'フラグON/OFFそれぞれの状態で機能が正しく動作し、切り替え時に不整合が発生しないかを確認する', 'フィーチャーフラグはテスト不要である', 'フラグの変数名が仕様書と一致するかだけを確認する'],
        correctAnswerIndex: 1,
        explanation: 'フィーチャーフラグのテストではフラグON時・OFF時の両方の動作確認と、フラグ切り替えタイミングでのデータ整合性やセッションへの影響を確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-151',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'A/Bテストと品質確認',
        question: 'A/Bテストを実施する際に、品質確認として最も重要な観点はどれか。',
        choices: ['AパターンとBパターンのどちらが見た目がきれいか', 'AパターンとBパターンの両方がクラッシュせず正しく動作し、計測データが正確に収集できているか', 'サーバーのコスト削減に繋がるかだけを確認する', 'Bパターンのみをテストする'],
        correctAnswerIndex: 1,
        explanation: 'A/Bテストでは各バリアントが機能的に正しく動作することと、割り当てロジックが統計的に適切で計測結果が信頼できることを品質面で確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'fl-152',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB/ISTQB public syllabus referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '振り返りとテストプロセス改善',
        question: 'スプリント終了後の振り返りでテストプロセスを改善するために、最も有用な情報はどれか。',
        choices: ['チームメンバーの出勤日数', '見逃した不具合の傾向・テスト実行にかかった時間・ブロッカーになった課題の記録', 'テストケースのフォントサイズ', 'バグトラッキングツールのUIデザイン'],
        correctAnswerIndex: 1,
        explanation: '振り返りによるプロセス改善には定量的なデータが必要です。見逃しバグの傾向分析・テスト効率・ブロッカーの記録を元に、次スプリントでの対策（テスト設計強化・環境整備・優先度見直しなど）を決めます。',
        reviewerStatus: 'reviewed',
    },
];

export const assumedProblems = questions;
export const mockExamQuestions = questions;
