// 制作者が独自に作成したALTA（テストアナリスト）学習問題。公式問題・公式本文は使用しない。
export const questions = [
    {
        id: 'alta-001',
        sectionRef: '1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト分析とテストケース設計の違い',
        question: 'テストアナリストがテスト分析を行う際の主な目的として、最も適切なものはどれか。',
        choices: ['テストケースの実行順序を決定する', 'テストベースから何をテストすべきかを識別し、テスト条件を定義する', 'テスト自動化のスクリプトを作成する', 'テストチームの人員配置を計画する'],
        correctAnswerIndex: 1,
        explanation: 'テスト分析では要件・仕様などのテストベースを分析し、テスト条件（何をテストするか）を識別します。テストケースを書く前の段階として、テスト対象の特性や制約を把握することが目的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-002',
        sectionRef: '1.4.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ローレベルテストケースとハイレベルテストケース',
        question: 'ハイレベルテストケースとローレベルテストケースの違いとして最も適切な説明はどれか。',
        choices: ['ハイレベルはシステムテスト用、ローレベルは単体テスト用である', 'ハイレベルは具体的なデータ値を持たない論理的なテストケース、ローレベルは実際の入力値と期待結果を持つ具体的なテストケースである', 'ハイレベルは経験豊富な担当者が作成し、ローレベルは初心者が作成する', 'ハイレベルはドキュメント化が不要で、ローレベルは必ずドキュメント化する'],
        correctAnswerIndex: 1,
        explanation: 'ハイレベルテストケースはテスト条件と期待結果を論理的に記述したもので、具体的なデータ値を持ちません。ローレベルテストケースはその具体的な実装であり、実際の入力値・前提条件・期待結果を含みます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-003',
        sectionRef: '3.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '同値分割法の適用',
        question: 'オンライン試験システムで受験年齢は18歳以上65歳以下に制限されている。同値分割法を適用した場合、有効同値クラスと無効同値クラスの組み合わせとして最も適切なものはどれか。',
        choices: ['有効: 18〜65歳、無効: 17歳以下と66歳以上', '有効: 20〜60歳、無効: それ以外すべて', '有効: 18歳と65歳のみ、無効: それ以外', '有効クラスは1つのみ、無効クラスは存在しない'],
        correctAnswerIndex: 0,
        explanation: '同値分割法では同じ処理をする入力の集合（クラス）に分けます。受験年齢18〜65歳が有効クラス、17歳以下と66歳以上がそれぞれ無効クラスになります。各クラスから代表値を1つ選んでテストします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-004',
        sectionRef: '3.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '境界値分析の適用',
        question: '配達料金は注文金額3000円未満は500円、3000円以上は無料というルールがある。境界値分析で優先してテストすべき値の組み合わせはどれか。',
        choices: ['1000円、2000円、4000円', '2999円、3000円、3001円', '1000円と5000円のみ', '3000円のみ'],
        correctAnswerIndex: 1,
        explanation: '境界値分析では条件が切り替わる境界付近（2999円、3000円、3001円）を重点的にテストします。境界の直前・境界値・直後の3点でoff-by-oneエラーなどを検出できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-005',
        sectionRef: '3.2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'デシジョンテーブルテストの作成',
        question: 'ローン審査で「年収300万以上」かつ「勤続2年以上」の両方を満たす場合に承認される。この条件のデシジョンテーブルで最低限必要なルール数はどれか。',
        choices: ['1つ', '2つ', '4つ', '8つ'],
        correctAnswerIndex: 2,
        explanation: '2つの条件（年収・勤続）それぞれにTrue/Falseがあるため、2² = 4通りのルールが必要です。条件の組み合わせを網羅することでデシジョンテーブルテストは機能します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-006',
        sectionRef: '3.2.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '状態遷移テストの適用',
        question: 'ATMで「カード挿入」→「PIN入力」→「金額選択」→「現金取出」→「カード返却」という流れがある。状態遷移テストで「無効なPIN入力3回」による「カードロック」への遷移を確認するテストとして、最も適切なものはどれか。',
        choices: ['正常なPINを3回入力してカードが返却されることを確認する', '誤ったPINを3回連続入力した後、カードが返却されずロック状態になることを確認する', 'PINを1回誤入力した後に正しいPINを入力して正常完了することを確認する', 'カードを挿入せずに金額入力画面が表示されないことを確認する'],
        correctAnswerIndex: 1,
        explanation: '状態遷移テストは特定のイベント（誤PIN3回）が正しい状態遷移（ロック状態）を引き起こすかを確認します。このテストではロック状態への遷移とカード返却なしという期待結果を検証します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-007',
        sectionRef: '3.2.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'クラシフィケーションツリー技法',
        question: 'クラシフィケーションツリー技法を使用するメリットとして最も適切なものはどれか。',
        choices: ['テストの実行時間を短縮する', '複数の分類軸（パラメーター）の組み合わせを体系的に整理し、テストカバレッジを視覚化できる', 'コードのカバレッジを100%にする', 'テスト自動化スクリプトを自動生成する'],
        correctAnswerIndex: 1,
        explanation: 'クラシフィケーションツリーは入力の分類（例: ブラウザ種類、OS種類、解像度）を木構造で整理し、どの組み合わせをテストするかを体系化します。テスト設計の一覧性と漏れの防止に有効です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-008',
        sectionRef: '3.2.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ペアワイズテストの目的',
        question: '5つの設定パラメーターがそれぞれ3〜5の選択肢を持つシステムをテストする場合、ペアワイズテストを採用する主な理由はどれか。',
        choices: ['すべての組み合わせを網羅してテストするため', '2つのパラメーターのすべての組み合わせをカバーしながらテストケース数を大幅に削減するため', 'テストを完全に自動化するため', 'テスト実行を担当者1人で行えるようにするため'],
        correctAnswerIndex: 1,
        explanation: 'ペアワイズテスト（オールペア法）は、すべての2因子間の組み合わせを少なくとも1回カバーすることで、全組み合わせより大幅に少ないテストケース数で高い欠陥検出率を実現します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-009',
        sectionRef: '3.3.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'エラー推測技法',
        question: '「パスワード変更」機能のテストにエラー推測を適用する場合、最も見落としがちなケースとして適切なものはどれか。',
        choices: ['正しい現在のパスワードと新しいパスワードを入力して変更成功する正常ケース', '新しいパスワードと確認用パスワードが一致しない場合・現在のパスワードが誤りの場合・最小文字数未満の場合など境界・異常入力のケース', 'パスワードの文字数を数える計算ロジック', 'UIボタンの配置デザイン'],
        correctAnswerIndex: 1,
        explanation: 'エラー推測では経験や直感をもとに欠陥が起きやすい箇所を推測します。パスワード機能では不一致・現パスワード誤り・文字数・特殊文字・連続同一パスワードなど、境界や異常入力が見落とされがちです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-010',
        sectionRef: '3.3.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '探索的テストの特徴',
        question: '探索的テストが特に有効な状況として最も適切なものはどれか。',
        choices: ['詳細な仕様書が完成しており、すべてのテスト条件が事前に定義できる場合', '仕様が不完全・変更頻繁な場合や、テスターの経験と学習を活かして予期しない欠陥を発見したい場合', 'リグレッションテストを毎回同じ手順で繰り返したい場合', 'コードのステートメントカバレッジを測定したい場合'],
        correctAnswerIndex: 1,
        explanation: '探索的テストはテスト設計・実行・学習を同時に行う技法です。仕様が曖昧・不完全な場合や、テスターの洞察力で予期しない欠陥パターンを発見したい場合に特に効果的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-011',
        sectionRef: '3.3.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥ベースのテスト技法',
        question: '欠陥ベースのテスト技法を使用する際の前提条件として最も適切なものはどれか。',
        choices: ['要件書が完全に作成されていること', '類似システムや過去の開発で発生した欠陥の情報（欠陥タクソノミーなど）が利用できること', 'テスト自動化ツールが導入されていること', 'コードの行数が1000行以下であること'],
        correctAnswerIndex: 1,
        explanation: '欠陥ベースのテスト（欠陥タクソノミー活用など）では、過去のプロジェクトや類似システムで発生しやすい欠陥パターンを参照し、それを引き起こしやすいテスト条件を設計します。過去データの蓄積が重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-012',
        sectionRef: '2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスク識別の観点',
        question: 'テストアナリストがリスクベーストテストでリスクを識別する際に重視すべき観点として最も適切なものはどれか。',
        choices: ['テストケースの見栄えとフォーマット', '発生頻度・影響度・ビジネス価値・検出困難性などの品質リスク観点', 'テスト担当者の個人的な好み', 'テストツールの操作マニュアル'],
        correctAnswerIndex: 1,
        explanation: '品質リスク識別では障害発生の可能性と影響度（ビジネスへの損害、安全性、法規制など）を組み合わせて評価します。高リスク項目を優先してテストリソースを配分することがリスクベーストテストの本質です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-013',
        sectionRef: '2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'リスクアセスメントの実施',
        question: '新しい決済機能のリスクアセスメントを行っている。「入力金額の四捨五入処理」のリスクレベルを評価する観点として最も適切なものはどれか。',
        choices: ['四捨五入処理のコードの行数', '誤った四捨五入による金銭的損害の可能性（影響度）と、この種の計算バグが発生する確率（発生可能性）の組み合わせ', '四捨五入処理を実装した担当者のキャリア年数', '処理速度が仕様書の基準を超えているか'],
        correctAnswerIndex: 1,
        explanation: 'リスクアセスメントは「発生可能性 × 影響度」で優先度を評価します。決済の四捨五入誤りは金銭的損害・法的問題・顧客信頼失墜など影響が大きく、計算ロジックの誤りは頻発しやすいため高リスクと評価されます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-014',
        sectionRef: '2.4.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスク軽減とテスト優先度付け',
        question: 'リスクベーストテストでテストケースに優先度を付ける主な目的はどれか。',
        choices: ['テストケースをアルファベット順に並べるため', '高リスクの機能を先にテストして重大な欠陥を早期に発見し、限られたリソースで最大の品質保証効果を得るため', 'テスト担当者の作業量を平等にするため', 'テスト実行時間を最短にするため'],
        correctAnswerIndex: 1,
        explanation: 'テストケースの優先度付けにより、限られた時間・リソースの中で最もリスクの高い機能を先にテストできます。これにより、時間切れになった場合でも最重要な品質リスクが確認済みとなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-015',
        sectionRef: '4.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '機能正確性テスト',
        question: 'ECサイトの消費税計算機能の機能正確性テストで最も重要な確認内容はどれか。',
        choices: ['税率変更ボタンのUIデザイン', '各種商品・割引・送料の組み合わせで税額計算が仕様通りの結果になること', 'データベースに格納されている商品名の表示', 'ページの読み込み速度'],
        correctAnswerIndex: 1,
        explanation: '機能正確性テストでは機能が「正しい結果を出力するか」を検証します。消費税計算の正確性確認では様々な入力パターン（整数・小数・割引適用・複数税率など）での計算結果が仕様と一致するかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-016',
        sectionRef: '4.2.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '使用性評価',
        question: 'Webアプリの使用性（ユーザビリティ）評価で最も効果的な手法はどれか。',
        choices: ['コードのバグ数を数える', '実際のユーザーに課題を与えてタスク達成率・所要時間・エラー発生数を観察するユーザビリティテスト', 'データベースのテーブル設計を確認する', 'サーバーのメモリ使用量を測定する'],
        correctAnswerIndex: 1,
        explanation: '使用性評価では実際のユーザーが代表的なタスクを達成できるか（有効性・効率・満足度）を測定します。ユーザビリティテストでは観察を通じてつまずきやすい箇所を直接発見できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-017',
        sectionRef: '4.2.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '相互運用性テスト',
        question: '相互運用性テスト（インターオペラビリティテスト）で確認する主な内容として最も適切なものはどれか。',
        choices: ['システムが障害から回復する時間', '自システムが他のシステムやコンポーネントと正しくデータ交換・連携できること', 'アプリのインストール手順の正確さ', 'UIの配色がブランドガイドラインに準拠していること'],
        correctAnswerIndex: 1,
        explanation: '相互運用性テストでは、自システムが他のシステム・外部API・データフォーマットと正しく通信・連携できるかを確認します。インターフェースの仕様違い・バージョン差異などの問題を検出します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-018',
        sectionRef: '4.2.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '移植性テスト',
        question: 'アプリケーションの移植性テストで確認すべき主な項目はどれか。',
        choices: ['アプリが特定のサーバー環境でのみ動作することを確認する', '異なるOS・ブラウザ・デバイス・バージョンの組み合わせで機能が正常に動作すること、および環境移行時の設定・データの移行が問題ないこと', '開発時のソースコードの行数が適切であること', 'パスワードの暗号化強度'],
        correctAnswerIndex: 1,
        explanation: '移植性テストでは、アプリが異なる環境（OS・ブラウザ・デバイス・クラウドプラットフォーム）に移行・適応できるか、インストール・アンインストールが問題ないかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-019',
        sectionRef: '5.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '要件レビューでのチェックリスト活用',
        question: '要件書のレビューにチェックリストを使用する主な利点はどれか。',
        choices: ['レビューにかかる時間を常に短縮できる', '確認すべき観点（完全性・一貫性・検証可能性・曖昧さなど）を見落としなく確認でき、レビューの品質を安定させられる', 'チェックリストに記載のない欠陥は存在しないと証明できる', '要件書の誤字脱字だけを自動修正できる'],
        correctAnswerIndex: 1,
        explanation: 'チェックリストを使ったレビューでは、過去の経験から導いた重要観点を毎回確認できます。確認漏れを防ぎ、レビュアーの経験に依存せず一定品質のレビューが可能になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-020',
        sectionRef: '5.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ユーザーストーリーのレビュー観点',
        question: 'アジャイル開発でユーザーストーリーをレビューする際に特に確認すべき観点（INVEST基準など）として最も適切なものはどれか。',
        choices: ['ストーリーが長いほど価値が高い', 'ストーリーが独立・交渉可能・価値あり・見積可能・適度なサイズ・テスト可能であること（INVEST）', 'ストーリーは必ず技術的な実装方法を含めること', 'ストーリーはプロダクトオーナーのみが理解できればよい'],
        correctAnswerIndex: 1,
        explanation: 'INVESTはユーザーストーリーの品質チェック基準です。独立性（I）・交渉可能性（N）・価値（V）・見積可能性（E）・適度なサイズ（S）・テスト可能性（T）の6つを確認します。特にテスト可能かどうかはテストアナリストが重視すべき観点です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-021',
        sectionRef: '6.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'キーワード駆動テスト',
        question: 'キーワード駆動テストの主な特徴として最も適切なものはどれか。',
        choices: ['テストスクリプトをすべて手動で記述する', 'テストケースをキーワード（アクション）と入力・期待値のデータで記述し、プログラミングスキルなしでもテスト設計と自動化実装を分離できる', 'テスト結果の記録を省略できる', 'データベースのみのテストに使用する'],
        correctAnswerIndex: 1,
        explanation: 'キーワード駆動テストでは「ログイン」「クリック」「検証」などのキーワードを使ってテスト手順を記述します。テスト設計者はプログラミングを知らなくてもテストを設計でき、自動化エンジニアはキーワードの実装に集中できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-022',
        sectionRef: '6.3.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト設計ツールの活用',
        question: 'テスト設計ツールを導入する主な目的として最も適切なものはどれか。',
        choices: ['テスト担当者の雇用を削減するため', 'テストケースの生成・管理・追跡可能性の確保を支援し、設計の効率と品質を向上させるため', 'テスト実行をすべて自動化するため', '開発者がコードを書く速度を上げるため'],
        correctAnswerIndex: 1,
        explanation: 'テスト設計ツールはテスト条件の整理・テストケース生成支援・要件とのトレーサビリティ確保・カバレッジ分析などを支援します。設計の一貫性向上と設計作業の効率化が主な目的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-023',
        sectionRef: '1.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト実装でのテストデータ管理',
        question: 'テスト実装段階でテストデータを管理する際の重要な考慮事項はどれか。',
        choices: ['すべてのテストで同じデータセットを使い回す', 'テストの独立性を保つため各テストに必要なデータを明確に定義し、テスト後にデータを元の状態に戻せるようにする', 'テストデータは手動で毎回入力する', 'テストデータはコードにハードコードする'],
        correctAnswerIndex: 1,
        explanation: 'テストデータ管理では独立性（他のテストの実行順序に影響されない）、再現性（同じ結果が得られる）、クリーンアップ（テスト後の状態のリセット）が重要です。共有データを使い回すとテスト間干渉が起きます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-024',
        sectionRef: '4.2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '機能完全性テスト',
        question: '機能完全性テストの目的として最も適切なものはどれか。',
        choices: ['システムが障害から回復できることを確認する', 'ユーザーが必要とするすべての機能が実装されており、要件として定義されたすべてのタスクを達成できることを確認する', 'システムの処理速度が仕様を満たすことを確認する', 'セキュリティ脆弱性がないことを確認する'],
        correctAnswerIndex: 1,
        explanation: '機能完全性とは、ユーザーが意図するすべての目的とタスクをシステムがカバーできているかという品質特性です。機能完全性テストでは、要件に定義されたすべての機能が実装されており、ユースケースが完結できるかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-025',
        sectionRef: '3.2.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '技法の組み合わせ適用',
        question: '複雑なWebフォームで「会員種別（3種）」「割引クーポン使用（有/無）」「支払方法（4種）」の組み合わせをテストする。最も効率的なアプローチはどれか。',
        choices: ['すべての組み合わせ（3×2×4=24通り）を全件テストする', 'ペアワイズテストで2つの要素間のすべての組み合わせをカバーし、テストケース数を削減する', '会員種別のみテストして他の要素は省略する', 'ランダムに5件だけ選んでテストする'],
        correctAnswerIndex: 1,
        explanation: 'ペアワイズテストにより3つのパラメーターの2因子組み合わせを全カバーしつつ、24通りを大幅に削減できます（通常9〜12件程度）。欠陥の多くは2因子の相互作用から発生するため、このアプローチで高い検出率が得られます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-026',
        sectionRef: '1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'テスト条件の識別',
        question: 'テストアナリストとして「在庫管理システムの入荷登録機能」をテスト分析する場合、識別すべきテスト条件として最も適切なものはどれか。',
        choices: ['入荷登録画面のCSS色指定', '有効な商品コードでの入荷登録・存在しない商品コード・数量0入力・数量上限超過・既存在庫との合算・入荷日の過去日/未来日など多様な入力条件', 'サーバーのディスク容量', 'テストを担当する人数'],
        correctAnswerIndex: 1,
        explanation: 'テスト条件の識別では機能仕様に基づき、正常ケース・エラーケース・境界値・ビジネスルールなどを網羅的に洗い出します。在庫管理であれば在庫合算ロジック・バリデーション・日付処理などが重要なテスト条件になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-027',
        sectionRef: '1.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト実行での欠陥報告',
        question: 'テスト実行中に発見した欠陥の報告において、テストアナリストが記載すべき最も重要な情報はどれか。',
        choices: ['テスト担当者の氏名だけ', '再現手順・テスト環境・実際の結果・期待する結果・重大度・優先度・添付証拠（スクリーンショット等）', 'テストケースのID番号のみ', '修正にかかる見積工数'],
        correctAnswerIndex: 1,
        explanation: '効果的な欠陥報告は開発者が欠陥を再現・修正できるよう支援します。再現手順・環境・期待値・実際値・重大度・証拠が揃うことで、開発者の調査時間を短縮し迅速な修正が可能になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-028',
        sectionRef: '3.3.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'チェックリストベーステスト',
        question: 'チェックリストベーステストを継続的に改善する最も効果的な方法はどれか。',
        choices: ['チェックリストの項目数を毎回2倍に増やす', '過去のレビューや欠陥データを分析して、見落とされた観点や頻出欠陥パターンをチェックリストに追加・更新する', 'チェックリストを他プロジェクトにそのまま流用する', 'チェックリストは最初に作成したら変更しない'],
        correctAnswerIndex: 1,
        explanation: 'チェックリストは「生きた文書」として継続改善が重要です。プロジェクト後の振り返りで見落とした欠陥パターンを特定し、それを防ぐ観点を追加することで、チェックリストの有効性を高め続けられます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-029',
        sectionRef: '2.4.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト実施と将来サイクルへの調整',
        question: 'テストサイクルで高リスク領域のテストを多く実施した結果、欠陥がほとんど発見されなかった。次のテストサイクルに向けて最も適切な調整はどれか。',
        choices: ['次サイクルでも同じ領域に同じリソースを投入する', '欠陥が少なかった領域のリスク再評価を行い、従来は低リスクと判断して十分にテストできなかった領域にリソースをシフトする', 'テストを次サイクルでは一切行わない', 'テスト担当者を交代させる'],
        correctAnswerIndex: 1,
        explanation: '欠陥が見つからなかった高リスク領域は、実際にはリスクが低かったか、テストが十分だったことを示します。次サイクルではリスク評価を更新し、まだ十分にテストできていない領域にリソースを再配分します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-030',
        sectionRef: '4.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '機能適切性テスト',
        question: 'ナビゲーションアプリの「最短ルート案内」機能の機能適切性テストで最も重要な確認事項はどれか。',
        choices: ['アプリのアイコンデザイン', '提示されるルートが実際に最短（または十分に合理的）であり、ユーザーの目的（目的地到着）を達成するために適切な機能を提供しているか', 'アプリのインストール時間', 'データベースのバックアップ設定'],
        correctAnswerIndex: 1,
        explanation: '機能適切性とは、機能がユーザーの目的達成に「どれだけ適しているか」という特性です。ナビアプリでは正確なルート計算、交通状況の反映、ユーザーの目的に合った提案ができているかを確認します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-031',
        sectionRef: '6.3.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト自動実行ツールの導入効果',
        question: 'テスト自動実行ツールを導入することで最も期待できる効果はどれか。',
        choices: ['テストケースの設計が不要になる', 'リグレッションテストを繰り返し高速・正確に実行でき、手動では難しい繰り返し作業や長時間テストを安定して実施できる', 'すべての欠陥を自動的に修正できる', 'テスト担当者が不要になる'],
        correctAnswerIndex: 1,
        explanation: 'テスト自動実行ツールはCI/CDパイプラインでのリグレッションテスト、繰り返し実行、長時間の耐久テストなどに最も効果を発揮します。ただし、テスト設計・探索的テスト・新機能評価は引き続き人間が担います。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-032',
        sectionRef: '1.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'SDLCにおけるテストアナリストの関与',
        question: 'アジャイル開発でテストアナリストがスプリント計画に参加する主な理由はどれか。',
        choices: ['コードを書くため', 'テスト観点からユーザーストーリーの受け入れ基準を明確化し、テスト工数を見積もり、テスト条件を早期に識別するため', '全体の会議時間を延ばすため', 'UIデザインを承認するため'],
        correctAnswerIndex: 1,
        explanation: 'アジャイル開発ではテストアナリストがスプリント計画に参加することで、ユーザーストーリーのテスト可能性確認・受け入れ基準の明確化・テスト工数の見積もりを早期に行えます。シフトレフトの実践です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-033',
        sectionRef: '3.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '境界値分析 2値BVA vs 3値BVA',
        question: '商品の在庫数が0〜999の範囲で有効とするシステムで、3値BVA（2点境界の両側）を適用した場合、最小値境界付近でテストすべき値はどれか。',
        choices: ['0のみ', '-1、0、1', '0、1のみ', '1のみ'],
        correctAnswerIndex: 1,
        explanation: '3値BVA（3-point BVA）では最小値の前（-1）、最小値（0）、最小値+1（1）の3つをテストします。2値BVAは境界と境界+1の2点ですが、3値BVAは境界の直前も含め、より多くの境界エラーを検出できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-034',
        sectionRef: '1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト実装とトレーサビリティ',
        question: 'テスト実装段階でトレーサビリティ（追跡可能性）を維持することの主な目的はどれか。',
        choices: ['コードの行数を記録するため', '各テストケースがどの要件・リスク・テスト条件に対応しているかを明確にし、カバレッジの確認と影響分析を可能にするため', 'テストの実行時間を短縮するため', 'テストツールのライセンスを管理するため'],
        correctAnswerIndex: 1,
        explanation: 'トレーサビリティにより要件↔テスト条件↔テストケースの対応が明確になります。要件変更時の影響範囲特定、カバレッジ不足の検出、テスト完了基準の確認に不可欠です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-035',
        sectionRef: '3.2.7',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ユースケーステストの設計',
        question: 'オンラインショッピングの「商品購入」ユースケースをテストする際、最も優先すべきシナリオはどれか。',
        choices: ['商品を検索してカートに追加・支払い完了・注文確認メール受信という基本フロー（メインシナリオ）と在庫切れ・決済失敗・セッションタイムアウトなどの代替フロー', '商品のデータベース格納形式の確認', 'サーバーのIPアドレス設定', 'アプリのビルドバージョン確認'],
        correctAnswerIndex: 0,
        explanation: 'ユースケーステストではメインシナリオ（正常な利用の流れ）を最初に検証し、次に代替フロー（エラー・例外・分岐）を検証します。ビジネス価値が高いメインフローの動作確認が最優先です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-036',
        sectionRef: '3.2.8',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '最善の技法の適用',
        question: '「資金移動処理」という複雑なビジネスロジックをテストする際、最も効果的な技法の組み合わせはどれか。',
        choices: ['探索的テストのみ', 'デシジョンテーブルテスト（複数条件の組み合わせ）＋境界値分析（金額の端）＋エラー推測（過去の欠陥パターン）を組み合わせる', '状態遷移テストのみ', 'ランダムテストのみ'],
        correctAnswerIndex: 1,
        explanation: '複雑なビジネスロジックには複数の技法を組み合わせるのが効果的です。デシジョンテーブルで条件の組み合わせを網羅し、境界値で端数処理エラーを検出し、エラー推測で過去の欠陥パターンに対応することで包括的にカバーできます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-037',
        sectionRef: '1.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'ALTA試験の前提資格',
        question: 'JSTQB Advanced Level テストアナリスト（ALTA）試験を受験するために一般的に必要な前提資格はどれか。',
        choices: ['前提資格は不要である', 'JSTQB Foundation Level（CTFL）の資格保有が一般的に求められる', 'ALTM資格の保有が必要である', 'IT企業での5年以上の就業が必要である'],
        correctAnswerIndex: 1,
        explanation: 'JSTQB Advanced Level試験の受験にはFoundation Level（基礎）の知識が前提とされています。CTFL資格保有が一般的な受験要件として定められています（公式サイトの最新情報をご確認ください）。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-038',
        sectionRef: '6.3.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストデータ準備ツールの活用',
        question: 'テストデータ準備ツールを使用する主な目的として最も適切なものはどれか。',
        choices: ['本番データをそのまま使ってテストするため', '大量の多様なテストデータの生成・マスキング・バリエーションの確保を自動化し、テスト条件の網羅性を高めるため', 'テストケースの実行を自動化するため', 'バグの修正を自動化するため'],
        correctAnswerIndex: 1,
        explanation: 'テストデータ準備ツールでは、大量のデータセット生成・本番データの匿名化（マスキング）・境界値や特殊ケースのデータ作成を効率化できます。手動でのデータ準備の手間を大幅に削減します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-039',
        sectionRef: '3.2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'デシジョンテーブルのルール削減',
        question: 'ある処理に「条件A（True/False）」「条件B（True/False）」「条件C（True/False）」の3つがあり、条件Aが真の場合は条件B・Cに関係なく結果Xになる。このとき、デシジョンテーブルのルール数を削減する方法として最も適切なものはどれか。',
        choices: ['ルールを削減できないので8通りすべてテストする', '条件AがTrueの場合はB・CをDon\'t Care（無関係）として1ルールに統合し、全体のルール数を削減する', '条件Cを省略して4ルールにする', 'ルール数は関係なくランダムに選ぶ'],
        correctAnswerIndex: 1,
        explanation: 'デシジョンテーブルでは、特定の条件が他の条件に関係なく結果を決定する場合、その条件をDon\'t Care（-）として統合できます。条件AがTrueなら残り2条件の4通りを1ルールに統合でき、効率的なテスト設計になります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'alta-040',
        sectionRef: '1.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTA syllabus v3.1.1 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト実行時のインシデント管理',
        question: 'テスト実行中に再現しない断続的な欠陥（フレイキーテスト）が発生した場合の最も適切な対応はどれか。',
        choices: ['再現しないのでバグではないと判断して無視する', '再現手順・環境情報・ログを詳細に記録し、再現条件の特定を試みながらインシデントとして報告する', 'そのテストケースを削除する', 'テスト担当者を交代させる'],
        correctAnswerIndex: 1,
        explanation: '断続的な欠陥は本番環境でも発生する可能性があるため、無視せずインシデントとして記録します。タイミング依存・環境依存・データ競合など様々な原因が考えられるため、詳細な記録と再現条件の調査が必要です。',
        reviewerStatus: 'reviewed',
    },
];

export const assumedProblems = questions;
export const mockExamQuestions = questions;
