// 制作者が独自に作成したALTM学習問題。公式問題・公式本文は使用しない。
export const questions = [
    {
        id: 'altm-001',
        sectionRef: '1.1.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト計画の活動',
        question: 'テストマネージャーがテスト計画を作成する際、最初に実施すべき活動として最も適切なものはどれですか？',
        choices: [
            'プロジェクトの目的・制約・リスクを分析し、テスト戦略の方向性を決める',
            'テストケースの優先順位を決定し、実行順序を確定する',
            'テストツールを選定してライセンスを取得する',
            '全テスト担当者のスキルマップを作成して教育計画を立案する',
        ],
        correctAnswerIndex: 0,
        explanation: 'テスト計画の最初のステップは、プロジェクトのコンテキスト（目的・制約・リスク）を正確に把握することです。この分析なしにテストケースの優先順位やツール選定を行うと、的外れな計画になりやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-002',
        sectionRef: '1.1.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストモニタリングとコントロール',
        question: 'テスト進捗をモニタリングしていたところ、計画より2日遅れていることが判明しました。テストマネージャーが最初に行うべき対応として最も適切なものはどれですか？',
        choices: [
            '直ちに全チームメンバーを残業させて遅れを取り戻す',
            '遅延の根本原因を特定し、コントロール策（リソース追加、スコープ調整等）を検討する',
            'ステークホルダーへの報告を遅らせて自己解決を待つ',
            'テストケースを無条件に削減してスケジュールに合わせる',
        ],
        correctAnswerIndex: 1,
        explanation: 'モニタリングで差異を検出した後は、コントロール活動として原因分析と対策検討が必要です。残業の強制やステークホルダーへの報告遅延は問題を悪化させる可能性があります。スコープ削減はリスクを考慮した上で判断すべきです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-003',
        sectionRef: '1.1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: 'テスト完了の活動',
        question: 'テスト完了フェーズで必ず実施すべき活動として最も適切なものはどれですか？',
        choices: [
            'テスト成果物のアーカイブと教訓のドキュメント化',
            'テスト環境を直ちに本番環境に転用する',
            '次プロジェクトのテストケースを先行して全件作成する',
            '欠陥管理ツールのアカウントを全員削除する',
        ],
        correctAnswerIndex: 0,
        explanation: 'テスト完了の活動には、テスト成果物（ログ、レポート、テストケース等）のアーカイブと、次のプロジェクトに活かすための教訓（レッスンラーンド）のドキュメント化が含まれます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-004',
        sectionRef: '1.2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ハイブリッドSDLCにおけるテストマネジメント',
        question: 'あるプロジェクトはフロントエンドをスクラムで開発し、バックエンドはウォーターフォールで開発するハイブリッドモデルを採用しています。テストマネージャーとして最も注意すべき課題はどれですか？',
        choices: [
            'スクラムチームの速度（ベロシティ）が低下すること',
            'ウォーターフォール側でバグが一切発生しないこと',
            'フロントエンドのスプリントが長すぎること',
            '2つの開発リズムの接点でテスト統合のタイミングが合わなくなるリスク',
        ],
        correctAnswerIndex: 3,
        explanation: 'ハイブリッドモデルでは、アジャイル側のイテレーションとウォーターフォール側のマイルストーンの接点でテスト統合のタイミングが合わなくなるリスクがあります。この同期問題を管理することがテストマネージャーの重要な役割です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-005',
        sectionRef: '1.3.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'リスク軽減活動としてのテスト',
        question: '決済機能を持つECサイトをリリース予定のプロジェクトで、テストマネージャーがリスクベーストアプローチを適用します。次の4つのリスク項目のうち、テストに最も多くのリソースを割り当てるべきはどれですか？\n\nA: 決済処理中のセッション切断による二重課金（発生可能性：高、影響：高）\nB: トップページの画像読み込みが1秒遅延する（発生可能性：中、影響：低）\nC: 管理画面の帳票CSVに余分な空白行が入る（発生可能性：低、影響：低）\nD: 商品検索の結果ソート順が設計と異なる（発生可能性：中、影響：中）',
        choices: [
            'B（発生可能性：中、影響：低）',
            'C（発生可能性：低、影響：低）',
            'A（発生可能性：高、影響：高）',
            'D（発生可能性：中、影響：中）',
        ],
        correctAnswerIndex: 2,
        explanation: 'リスクベーストテストでは「発生可能性×影響度」でリスクレベルを算出し、高リスク項目に優先的にリソースを配分します。選択肢Aは発生可能性も影響も高く、財務的損害と顧客信頼の喪失を招くため最優先です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-006',
        sectionRef: '1.3.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '品質リスクの識別',
        question: '品質リスクを識別する手法として適切でないものはどれですか？',
        choices: [
            '過去の類似プロジェクトの欠陥データを参照する',
            'ドメイン専門家へのインタビューやワークショップを実施する',
            '開発完了後に全テストを実行してから識別する',
            'チェックリストやリスクテンプレートを活用する',
        ],
        correctAnswerIndex: 2,
        explanation: '品質リスクの識別はテスト計画段階（開発の初期）に実施すべき活動です。開発完了後に識別しては、リスクに基づいたテスト計画の効果が失われます。過去データ参照・専門家インタビュー・チェックリスト活用は適切な識別手法です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-007',
        sectionRef: '1.3.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '品質リスクアセスメント',
        question: 'リスクアセスメントで「発生可能性」と「影響度」を評価する際、影響度を決定する要素として最も適切なものはどれですか？',
        choices: [
            'テストチームの規模と予算',
            'テストケースの総数と自動化率',
            'ビジネス上の損害や利用者への影響の大きさ',
            'ソースコードの行数と複雑度',
        ],
        correctAnswerIndex: 2,
        explanation: 'リスクの影響度はビジネス観点で評価します。具体的には財務的損害、ブランド毀損、規制違反リスク、利用者への悪影響の大きさが基準です。テストチームの規模やコード行数は影響度の評価基準ではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-008',
        sectionRef: '1.3.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '適切なテストによる品質リスク軽減',
        question: 'あるWebアプリに「同時接続ユーザーが急増した際にDBコネクションプールが枯渇するリスク」が識別されています。このリスクを最も効果的に軽減するテストアプローチはどれですか？',
        choices: [
            'ユニットテストでDBアクセスクラスの全メソッドを100%カバーする',
            '本番リリース後にエラーログを監視してコネクション枯渇を検知する',
            'コードレビューでコネクションプールの設定値を目視確認するだけにする',
            '想定最大負荷の1.5倍のユーザー数で負荷テストを実施し、コネクション数を監視する',
        ],
        correctAnswerIndex: 3,
        explanation: '「同時接続増加によるコネクション枯渇」は性能・負荷リスクです。このリスクを軽減するには、実際の負荷条件下での動作確認（負荷テスト）が最も効果的です。ユニットテストやコードレビューのみでは動的な枯渇現象を捉えられません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-009',
        sectionRef: '1.3.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'リスクベーストテストの技法',
        question: 'リスクマトリクスを用いたリスクベーストテストにおいて、「発生可能性：低、影響度：高」に分類されたリスクへの対応として最も適切なものはどれですか？',
        choices: [
            'テストリソースをほとんど割り当てず、無視する',
            '発生可能性が低いため、テストを完全に省略する',
            '影響度が高いため、軽量なテストを実施しつつコンティンジェンシープランを準備する',
            'このカテゴリは常に最高優先度として全リソースを投入する',
        ],
        correctAnswerIndex: 2,
        explanation: '「発生可能性：低、影響度：高」のリスクは中程度のリスクレベルです。発生頻度は低くても起きた際の被害が大きいため、軽量なテストで存在を確認しつつ、万一発生した際の対応計画（コンティンジェンシープラン）を準備するのが適切です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-010',
        sectionRef: '1.4.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストアプローチの選択',
        question: '安全性が要求される医療機器ソフトウェアのプロジェクトで、テストアプローチを選択する際に最も重視すべき要因はどれですか？',
        choices: [
            '規制・標準への適合要件とトレーサビリティの確保',
            '開発チームの好みと慣れているテスト技法',
            '最も安価なテストツールの利用可能性',
            'テスト自動化率を最大化できること',
        ],
        correctAnswerIndex: 0,
        explanation: '医療機器ソフトウェアはIEC 62304などの規制標準への適合が必須です。テストアプローチは規制要件を満たし、要件から欠陥までのトレーサビリティを確保できるものを優先する必要があります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-011',
        sectionRef: '1.4.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト目的の定義',
        question: 'プロジェクト開始時にテスト目的を定義する主な理由として最も適切なものはどれですか？',
        choices: [
            'テスト担当者が毎日の業務スケジュールを自動的に決定できるようにする',
            '開発者がコーディングを先行してテストを後回しにできるようにする',
            'テストフェーズを省略できる条件を事前に定義する',
            'テストの対象・範囲・完了基準を明確にし、ステークホルダーの期待を合わせる',
        ],
        correctAnswerIndex: 3,
        explanation: 'テスト目的の定義は、何をテストするか（対象）、どの範囲まで（スコープ）、いつ終わりにするか（完了基準）を明確にし、開発チーム・マネジメント・顧客などのステークホルダー間で期待を揃えるために行います。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-012',
        sectionRef: '1.5.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト改善プロセス（IDEAL）',
        question: 'IDEALモデルに基づいてテストプロセス改善を推進しています。現在、過去プロジェクトのメトリクスを収集・分析し、現状の強みと弱みを特定している段階です。この活動はIDEALのどのフェーズに相当しますか？',
        choices: [
            'I：開始（Initiating）',
            'D：診断（Diagnosing）',
            'E：確立（Establishing）',
            'A：活動（Acting）',
        ],
        correctAnswerIndex: 1,
        explanation: 'IDEALの「D：診断（Diagnosing）」フェーズでは、現状のプロセスを評価し、強みと弱みを特定します。メトリクス収集・分析を通じて改善すべき領域を特定するのはまさにこのフェーズの活動です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-013',
        sectionRef: '1.5.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'モデルベースのテストプロセス改善',
        question: 'TMMi（テスト成熟度モデル統合）を活用してテストプロセス成熟度を評価する目的として最も適切なものはどれですか？',
        choices: [
            '現在のテストプロセスの成熟度レベルを客観的に測定し、具体的な改善方向を示す',
            '個々のテスト担当者のスキルを昇給評価に直接使用する',
            '競合他社のテストプロセスを模倣するための基準を得る',
            'テスト自動化ツールの選定基準を定める',
        ],
        correctAnswerIndex: 0,
        explanation: 'TMMiはテストプロセスの成熟度を客観的なモデルで測定し、組織が段階的に改善できる方向性（ロードマップ）を提供します。個人評価や競合模倣、ツール選定が主目的ではありません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-014',
        sectionRef: '1.5.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'ふりかえり',
        question: 'スプリントレトロスペクティブで「テスト完了が毎スプリントで遅延する」という問題が繰り返し挙げられています。テストマネージャーとして最も効果的な対応はどれですか？',
        choices: [
            '遅延したメンバーを記録し、人事評価に反映させる',
            '遅延の根本原因（テスト設計不足・環境不安定・仕様変更など）を分析し、次スプリントの改善アクションを具体的に定義して実施する',
            'レトロスペクティブの開催頻度を減らして議論の時間を削る',
            'テストスコープを毎回削減して期間内に収める',
        ],
        correctAnswerIndex: 1,
        explanation: 'ふりかえり（レトロスペクティブ）の価値は、繰り返す問題の根本原因を特定し、具体的な改善アクションを定義・実施することにあります。人事評価への反映や頻度削減は問題解決につながりません。スコープ削減は品質リスクを増大させます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-015',
        sectionRef: '1.6.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ツール導入のためのよい実践',
        question: 'テスト自動化ツールを新規導入する際の適切な進め方として最も適切なものはどれですか？',
        choices: [
            'パイロット導入で小規模プロジェクトに適用し、効果と課題を評価してから展開を判断する',
            '全テストケースを一度に自動化してから評価する',
            'ツールベンダーの推奨スペックのみを基準に選定する',
            '最も多くの機能を持つツールを無条件に選ぶ',
        ],
        correctAnswerIndex: 0,
        explanation: 'ツール導入のよい実践では、小規模なパイロット（概念実証）から始めることが推奨されます。一度に全件自動化すると失敗リスクが高く、ベンダー推奨スペックや機能数だけでの選定は現場ニーズと合わない可能性があります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-016',
        sectionRef: '1.6.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '選定プロセスの考慮事項とROI評価',
        question: 'テスト管理ツールの導入ROIを評価する場合、コスト面で考慮すべき項目として適切でないものはどれですか？',
        choices: [
            'ライセンス費用とサポート費用',
            'ツール導入・設定にかかる初期工数',
            '競合他社のツール導入意思決定の速さ',
            'チームのトレーニングと習熟にかかる工数',
        ],
        correctAnswerIndex: 2,
        explanation: 'ROI評価では自組織のコスト（ライセンス、導入工数、トレーニング工数等）と効果（削減工数、品質向上等）を比較します。競合他社の意思決定速度は自組織のROI計算には直接関係しません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-017',
        sectionRef: '2.1.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストマネジメント活動のためのメトリクス',
        question: '「テスト密度」メトリクスを計算する式として最も適切なものはどれですか？',
        choices: [
            'テスト実行件数 ÷ テスト担当者数',
            '発見欠陥数 ÷ テスト実行時間（時間）',
            'パステスト数 ÷ フェイルテスト数',
            'テストケース数 ÷ コードの規模（機能点数またはLOC）',
        ],
        correctAnswerIndex: 3,
        explanation: 'テスト密度はコードの単位規模あたりのテストケース数を示すメトリクスです。一般に「テストケース数 ÷ 機能点数（またはLOC）」で計算します。テストカバレッジの厚さを評価するために使用されます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-018',
        sectionRef: '2.1.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'モニタリング・コントロール・完了',
        question: 'バーンダウンチャートを使用してテスト進捗をモニタリングしています。計画線に対して実績線が大きく上方に位置している場合、何を示していますか？',
        choices: [
            'テストが計画より速く進んでいる',
            'テストの品質が計画より高い',
            '欠陥の発見数が予想より少ない',
            '残作業が計画より多く、テストが遅延していることを示している',
        ],
        correctAnswerIndex: 3,
        explanation: 'バーンダウンチャートは残作業量を縦軸に取ります。実績線が計画線より上方にある場合、残作業が計画より多い（消化が遅れている）ことを意味し、テストが遅延していることを示します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-019',
        sectionRef: '2.1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'テスト報告',
        question: 'プロジェクトの週次ステータスレポートをCTO向けに作成します。CTOは技術詳細よりも意思決定に必要な情報を重視します。最も適切なレポート内容はどれですか？',
        choices: [
            'テストケースごとの実行ログと詳細なエラーメッセージの全一覧',
            'テスト環境の構成情報と使用ツールの詳細仕様',
            'テスト担当者ごとの日次作業時間の集計表',
            'リリース判断に関わるリスク状況、主要メトリクスサマリー、要対応事項',
        ],
        correctAnswerIndex: 3,
        explanation: 'マネジメント向けテストレポートはオーディエンスのニーズに合わせて作成します。CTOなど意思決定者には、リリース判断に必要なリスク状況、品質状態のサマリー、エスカレーションが必要な事項を簡潔に伝えることが重要です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-020',
        sectionRef: '2.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストに関する活動の見積り',
        question: '類推見積り（アナロジー見積り）の説明として最も適切なものはどれですか？',
        choices: [
            '過去の類似プロジェクトの実績データを参照し、現プロジェクトの工数を推定する方法',
            '専門家が直感のみに基づいて工数を算出する方法',
            'テストケース1件あたりの固定コストに件数を掛けて算出する方法',
            '全チームメンバーが個別に見積もり、最大値を採用する方法',
        ],
        correctAnswerIndex: 0,
        explanation: '類推見積りは、過去に実施した類似プロジェクトの実績（工数・規模・複雑度）を参照し、現プロジェクトとの類似点・相違点を考慮して工数を推定する手法です。実績データの蓄積が精度向上の鍵です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-021',
        sectionRef: '2.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テスト工数に影響を与える可能性のある要因',
        question: '同規模のプロジェクトでも、テスト工数が大幅に増加する要因として最も適切なものはどれですか？',
        choices: [
            'テストマネージャーの資格保有状況',
            'プロジェクト室のデスク配置',
            '開発言語としてJavaを使用していること',
            '要件の変更頻度が高く、テストケースの修正・追加が頻繁に発生する',
        ],
        correctAnswerIndex: 3,
        explanation: '要件の変更頻度はテスト工数に直接影響します。要件が頻繁に変わるとテストケースの作り直しや再実行が必要になり、工数が大幅に増加します。その他の選択肢（資格・デスク配置・言語）は工数への影響が限定的です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-022',
        sectionRef: '2.2.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'テスト見積り技法の選択',
        question: '新規性が高く過去の類似データがほとんど存在しない先端技術プロジェクトで、テスト工数を見積もる場合に最も適切な手法はどれですか？',
        choices: [
            '過去プロジェクトの平均値をそのまま流用する類推見積り',
            'ポイントカウント法（機能点数ベース）のみで厳密に算出する',
            '複数の専門家の知見を組み合わせるデルファイ法や専門家判断を活用する',
            'チームの希望工数を集計して上司が最終調整する',
        ],
        correctAnswerIndex: 2,
        explanation: '先端技術や新規性の高いプロジェクトでは過去データが少ないため、類推見積りの精度が低下します。このような場合、複数の専門家の判断を構造的に集約するデルファイ法や専門家判断が適切です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-023',
        sectionRef: '2.3.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '欠陥のライフサイクル',
        question: '欠陥管理ツールで欠陥のステータスが「クローズ」になる条件として最も適切なものはどれですか？',
        choices: [
            '開発者が修正を完了してプルリクエストを提出した時点',
            '欠陥を発見したテスト担当者が報告書を作成した時点',
            'テスト担当者が修正を確認し、期待通りに動作することを検証した後',
            'マネージャーが欠陥レポートを読んだ時点',
        ],
        correctAnswerIndex: 2,
        explanation: '欠陥のライフサイクルでは、開発者による修正だけでクローズになるわけではありません。テスト担当者が修正内容を検証（確認テスト）し、期待動作を確認して初めてクローズされます。これにより修正漏れや誤修正を防げます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-024',
        sectionRef: '2.3.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '機能横断的な欠陥マネジメント',
        question: '欠陥マネジメントを機能横断的に行う主な目的として最も適切なものはどれですか？',
        choices: [
            '開発・テスト・運用・ビジネス部門が欠陥情報を共有し、組織全体の品質改善に活かす',
            '開発部門のみが欠陥情報を管理し、他部門には共有しない',
            '欠陥の修正を外注することで社内工数を削減する',
            '欠陥レポートの書式を標準化して書類作業を自動化する',
        ],
        correctAnswerIndex: 0,
        explanation: '機能横断的な欠陥マネジメントは、欠陥情報を開発・テスト・運用・ビジネス等の各部門が共有し、根本原因分析や再発防止策を組織全体で取り組むことを目的とします。情報の囲い込みは改善機会を失わせます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-025',
        sectionRef: '2.3.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K1',
        topic: '欠陥レポート情報',
        question: '欠陥レポートに必須で含めるべき情報として最も適切なものはどれですか？',
        choices: [
            '欠陥を発見したテスト担当者の給与情報',
            '再現手順、実際の結果、期待される結果、深刻度',
            '開発者の名前と修正予定時間の自己申告',
            '他プロジェクトで発生した類似欠陥の全リスト',
        ],
        correctAnswerIndex: 1,
        explanation: '欠陥レポートの基本情報として、再現手順（再現できること）・実際の結果（何が起きたか）・期待される結果（何であるべきか）・深刻度（ビジネス影響）は必須です。これらがあることで開発者が的確に修正できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-026',
        sectionRef: '2.3.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '欠陥レポート情報を用いたプロセス改善アクションの定義',
        question: '過去6ヶ月の欠陥データを分析したところ、「入力値検証不足」カテゴリの欠陥が全体の45%を占め、そのほとんどが結合テスト後に発見されていることがわかりました。最も効果的なプロセス改善アクションはどれですか？',
        choices: [
            '結合テストの実行件数を2倍に増やす',
            '単体テスト段階での入力値検証テストを強化し、早期に欠陥を検出するようにする',
            '入力値検証の欠陥を今後は記録しないことにする',
            'テストチームの人員を増員してすべての欠陥修正に対応する',
        ],
        correctAnswerIndex: 1,
        explanation: '欠陥の多くが結合テスト後に発見されているのは、より早い段階（単体テスト）で検出できるはずの欠陥が見逃されていることを示します。入力値検証の欠陥を単体テスト段階で捕捉するよう改善すると、手戻りコストが大幅に削減できます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-027',
        sectionRef: '3.1.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '4つの能力領域における代表的なスキル',
        question: 'テストチームに求められる4つの能力領域（テスト技術・ソフトウェア技術・ドメイン知識・対人スキル）のうち、「テストアーキテクチャの設計」に最も直接関連する能力領域はどれですか？',
        choices: [
            'ドメイン知識（業務知識）',
            'テスト技術（テスト技法・プロセス・ツール）',
            '対人スキル（コミュニケーション・交渉）',
            'ソフトウェア技術（開発・アーキテクチャ）',
        ],
        correctAnswerIndex: 1,
        explanation: 'テストアーキテクチャ（テスト構造・技法・フレームワーク）の設計は、テスト技術能力領域に属します。テスト技法の選択、テスト設計パターン、テストフレームワーク構築などがこの領域のスキルです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-028',
        sectionRef: '3.1.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストチームがうまくいくために必要なマネジメントスキル',
        question: 'テストマネージャーがチームの生産性を高めるために最も効果的なマネジメントスキルはどれですか？',
        choices: [
            'チームメンバーの強みを把握し、適切な権限委譲と明確な目標設定を行う',
            '全員のタスクを毎日マネージャーが直接割り当て、作業を細かく監視する',
            '残業を奨励して作業時間を最大化する',
            '定期的なミーティングを削減してコミュニケーションを最小化する',
        ],
        correctAnswerIndex: 0,
        explanation: '効果的なマネジメントは、メンバーの強みを活かした役割分担と、自律性を持って仕事に取り組めるような適切な権限委譲、および達成可能で明確な目標設定から生まれます。マイクロマネジメントや残業強制は長期的に生産性を下げます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-029',
        sectionRef: '3.1.6',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'モチベーションを上げる/下げる要因',
        question: 'テストチームのモチベーションを下げる要因として最も典型的なものはどれですか？',
        choices: [
            '挑戦的な技術課題に取り組む機会が多い',
            '成果が認められ、フィードバックが定期的に行われる',
            'テストの成果や貢献がプロジェクト全体で過小評価され、承認されない',
            'スキルアップのための研修やカンファレンス参加が奨励される',
        ],
        correctAnswerIndex: 2,
        explanation: 'テストチームのモチベーションを下げる主要因の一つは、テスト活動の成果や貢献が組織・プロジェクトから認められないことです。「テストはコスト」という見方が浸透している組織では特にこの問題が起きやすくなります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-030',
        sectionRef: '3.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: '品質コスト',
        question: '品質コスト（CoQ）の分析を実施したところ、「外部失敗コスト（本番障害対応・クレーム対応）」が総品質コストの60%を占めることがわかりました。このデータから導かれる最も適切な改善方向はどれですか？',
        choices: [
            '本番障害対応チームの人員を増員してコストを吸収する',
            'テスト工程での欠陥検出（内部失敗コスト・評価コスト）を強化し、外部失敗コストを削減する',
            '外部失敗コストは顧客が負担すべきなので変更不要',
            '品質コストの分析自体を廃止してコスト計測をやめる',
        ],
        correctAnswerIndex: 1,
        explanation: '外部失敗コストが高い場合、テスト・レビュー段階での欠陥検出（評価コスト・内部失敗コスト）を強化することで、本番障害を未然に防ぎ外部失敗コストを削減できます。品質コストの最適化は評価コスト投資による外部失敗コストの圧縮にあります。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-031',
        sectionRef: '3.2.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストの費用対効果の関係',
        question: 'テスト活動のROI（投資対効果）を説明する際に、ステークホルダーに伝えるべき最も重要な視点はどれですか？',
        choices: [
            'テスト担当者の人件費は無視してよい',
            '早期にテストコストを投資することで、後工程での修正コスト（指数関数的に増大）を削減できる',
            'テストを実施すると必ず開発コストが2倍になる',
            'テストへの投資はプロジェクト完了後にのみ効果が現れる',
        ],
        correctAnswerIndex: 1,
        explanation: 'テスト投資のROIの核心は「欠陥検出の早期化によるコスト削減」です。欠陥修正コストは検出が遅れるほど指数関数的に増大するため、早期のテスト投資は後工程での多大な修正コストを回避し、結果的に高いROIをもたらします。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-032',
        sectionRef: '1.2.5',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'さまざまなテストレベルにおけるテストマネジメント活動',
        question: 'システムテストレベルでテストマネジメントを行う場合、単体テストレベルと比較して特に注意すべき管理上の課題はどれですか？',
        choices: [
            '単体テストよりもモックオブジェクトの作成数が増える',
            'システムテストではコードカバレッジの測定が必須になる',
            '単体テストよりもテスト自動化が困難なため、手動テストを完全に廃止する',
            '複数チームの成果物が統合されるため、依存関係・テスト環境・スケジュール調整が複雑になる',
        ],
        correctAnswerIndex: 3,
        explanation: 'システムテストレベルでは複数の開発チームの成果物が統合されます。そのためインターフェース依存関係の管理、統合テスト環境の整備、複数チーム間のスケジュール調整など、マネジメント上の複雑性が単体テストより大幅に増加します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-033',
        sectionRef: '1.2.4',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'さまざまなSDLCモデルにおけるテストマネジメント活動',
        question: 'スクラムを採用したプロジェクトでのテストマネジメントの特徴として最も適切なものはどれですか？',
        choices: [
            '全テスト設計をスプリント開始前に一括完了する',
            'テストはリリース直前のスプリントのみに集中させる',
            'スクラムではテストマネージャーが全テスト作業を一人で実施する',
            'スプリント内にテスト設計・実行・報告を組み込み、継続的にフィードバックを提供する',
        ],
        correctAnswerIndex: 3,
        explanation: 'スクラムではスプリント内に開発からテストまでを完結させるインクリメンタルな進め方が基本です。テストマネージャーは各スプリントでテスト設計・実行・メトリクス報告を完結させ、継続的にチームへフィードバックを提供します。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-034',
        sectionRef: '',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストプロセス',
        question: 'テストプロセスにおいて「テスト分析」フェーズの主な成果物はどれですか？',
        choices: [
            '実行済みテストケースの結果ログ',
            '欠陥レポートの累積件数',
            'テストの対象（何をテストするか）を明確にしたテスト条件リスト',
            '自動化スクリプトのソースコード',
        ],
        correctAnswerIndex: 2,
        explanation: 'テスト分析フェーズでは、テストベース（要件・設計・リスクなど）を分析し「何をテストするか」を定義します。主な成果物はテスト条件（テスト対象の特性・機能・リスク項目）のリストです。実行ログや欠陥レポートは後工程の成果物です。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-035',
        sectionRef: '1.4.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'プロジェクトテスト戦略',
        question: 'あなたはBtoC金融サービスの大規模改修プロジェクトのテストマネージャーです。以下の条件でテスト戦略を選択します。「規制要件あり・前バージョンから大量の変更・高可用性要件・6ヶ月のリリース期限」最も適切なテスト戦略はどれですか？',
        choices: [
            '探索的テスト中心で仕様書は参照しない戦略',
            '規制適合確認・リスクベーストテスト・リグレッションテストを組み合わせ、トレーサビリティを確保した戦略',
            '開発者がユニットテストのみを実施し、システムテストは省略する戦略',
            '全テストケースを手動で実施し、自動化は一切行わない戦略',
        ],
        correctAnswerIndex: 1,
        explanation: '金融サービスの大規模改修では、規制要件への適合（トレーサビリティ必須）・大量変更によるリグレッションリスク・高可用性のための性能テストが必要です。これらを組み合わせたリスクベーストの包括的戦略が適切です。探索的テスト単体や開発者ユニットテストのみでは要件を満たせません。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-036',
        sectionRef: '1.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'ステークホルダーとの関係',
        question: 'テストマネージャーが開発マネージャーと意見が対立した際（例：リリース可否の判断）に最も適切な対応はどれですか？',
        choices: [
            '常に開発マネージャーの判断に従い、異論を唱えない',
            'メールで抗議書を作成し、全関係者に一斉送信する',
            'テストチームの判断が常に正しいため、開発マネージャーを説得するまで議論を続ける',
            'データ（欠陥件数・残リスク・テストカバレッジ）に基づいて客観的に状況を説明し、共同でリスクを評価する',
        ],
        correctAnswerIndex: 3,
        explanation: 'ステークホルダー間の対立では、感情的な対立ではなく客観的なデータに基づく議論が効果的です。欠陥データ・残存リスク・カバレッジなどの事実を共有し、リスクの認識を揃えた上で共同で意思決定することが望ましいです。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-037',
        sectionRef: '2.1.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: 'テストメトリクス',
        question: '「欠陥除去効率（DRE）」を計算する式として最も適切なものはどれですか？',
        choices: [
            '総テスト実行時間 ÷ 発見欠陥数',
            'テスト工数 ÷ 開発工数 × 100',
            '(テスト中に発見した欠陥数) ÷ (テスト中発見欠陥数 + 本番リリース後発見欠陥数) × 100',
            'クローズ欠陥数 ÷ オープン欠陥数',
        ],
        correctAnswerIndex: 2,
        explanation: '欠陥除去効率（DRE：Defect Removal Efficiency）は、テスト工程で取り除いた欠陥の割合を示します。計算式は「テスト中発見数 ÷ (テスト中発見数 + リリース後発見数) × 100」です。DREが高いほどテスト工程が効果的に欠陥を捕捉しています。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-038',
        sectionRef: '1.5.2',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'テストプロセス改善',
        question: '組織のテスト成熟度評価でスクリプトなし（アドホック）のテストが多く、テストケース再利用率が低いことが判明しました。具体的な改善アクションとして最も適切なものはどれですか？',
        choices: [
            '全テストケースを廃棄し、毎回ゼロから作成する方針にする',
            'テスト設計プロセスを確立し、テストケースをリポジトリで管理・再利用できる仕組みを整備する',
            '探索的テストを全面禁止にする',
            'テスト担当者全員を新しいメンバーに交代させる',
        ],
        correctAnswerIndex: 1,
        explanation: 'アドホックテストが多くテストケース再利用率が低い場合、テスト設計プロセスの標準化とテストケースリポジトリの整備が効果的な改善策です。これにより再現性・効率性・品質の向上が図れます。探索的テスト全面禁止は別の価値を失わせます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-039',
        sectionRef: '3.2.1',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K2',
        topic: '品質コスト',
        question: '品質コスト（CoQ）の4つのカテゴリのうち「予防コスト」に分類されるものはどれですか？',
        choices: [
            '本番環境で発生した障害への対応工数',
            '欠陥修正後の確認テスト工数',
            'テスト担当者向けのテスト技法研修費用',
            '受入テストでの欠陥再現調査工数',
        ],
        correctAnswerIndex: 2,
        explanation: '予防コストは欠陥の発生を未然に防ぐための投資です。テスト技法の研修・コードレビュープロセス構築・品質基準の整備などが含まれます。障害対応・確認テスト・欠陥再現調査は外部失敗コストまたは内部失敗コストに分類されます。',
        reviewerStatus: 'reviewed',
    },
    {
        id: 'altm-040',
        sectionRef: '2.1.3',
        sourcePolicy: 'original',
        officialQuestionUsed: false,
        certificationReference: 'JSTQB ALTM syllabus v3.0 referenced only as topic map',
        loCode: '',
        kLevel: 'K3',
        topic: 'テストプロセス全体の統合',
        question: 'あるプロジェクトでシステムリリース2週間前にクリティカルな欠陥が10件残存しています。テストマネージャーはステークホルダーにリリース判断を仰ぐためのレポートを作成します。レポートに含めるべき最も重要な情報の組み合わせはどれですか？',
        choices: [
            '残存欠陥のビジネス影響度・回避策の有無・修正完了見込み・リリース延期した場合のコストとリスク',
            'テスト担当者の氏名と各自の担当テスト件数の一覧',
            'テスト環境のサーバースペックとネットワーク構成図',
            '過去3ヶ月間の欠陥発見数の推移グラフのみ',
        ],
        correctAnswerIndex: 0,
        explanation: 'リリース可否の意思決定を促すレポートには、残存欠陥のビジネスへの影響・顧客への回避策・修正完了時期の見通し・リリース延期した場合のコスト比較が必要です。ステークホルダーがリスクを定量的に判断できる情報を提供することがテストマネージャーの役割です。',
        reviewerStatus: 'reviewed',
    },
];

export const assumedProblems = questions;
export const mockExamQuestions = questions;
